### ISSUE TITLE
Replace ODK Validate with directly calling JavaRosa

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#113]
It seems like a waste for pyxform to have to embed ODK Validate just to confirm a form works. We should replace it with directly calling JavaRosa.

This issue is blocked because we need an upstream fix: https://github.com/opendatakit/javarosa/issues/58.

**Comment by lognaturel** [comment]
This is not actionable; let's open if/when JavaRosa gets those changes.
