### ISSUE TITLE
Release next version of pyxform

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#115]
I'd like to explore what it would take to release an updated version of `pyxform` and what we can all do to help.

Here are the things that I think are must-haves:
- ~#114 Use Validate 1.5.0 -- this will allow use of new XPath functions and `range`~ closed in #116!
- #79 Support for numeric range questions -- this is now in JavaRosa but we have to agree on an approach for XLSForm
- ~#85 Replace curly quotes with normal quotes -- this breaks a lot of people copying examples; @dorey is on it.~ closed in #118!

I think if there's a release scheduled on the horizon we might also get excited about fixing other long-standing bugs!

The ODK core tools are now releasing on the last Sunday of each month. From our end, the ideal would be to have a pyxform release around June 19th so we can update all the tools that depend on it (online/offline form converters, etc).

@ukanga what do you think?

**Comment by ukanga** [comment]
Thank you @lognaturel for putting this together. 
- It seems you are already on #114, not sure if you will be working on hooking it up to a windows CI before we merge that in.
- #79 requires some movement, no clear spec has emerged. If the discussion on that can be completed I can work on implementation.
- #85 will you please assign it to @dorey  on the issue, you have pointed out that he is working on this.

**Comment by lognaturel** [comment]
Thanks @ukanga!

I was going to manually try it on Windows. I do really like @lindsay-stevens suggestion to use AppVeyor. If you're open to a pull request configuring that, I will try it out. There may be a limit to what I can do without being part of the organization and I'll ping you as needed.

Similarly, only organization members can assign issues but it looks like @dorey was so fast he didn't even need assigning anyway. 😊

Will try to move the conversation along on #79! It would be very helpful to get some comments from XLSForm masters. I've mostly been playing on the XML side of things so I may not have the right instincts.

**Comment by ukanga** [comment]
@lognaturel I should probably have communicated this, all the issues here have been resolved. The only issue that has held me back is we need a new release of ODK Validate that includes the fix https://github.com/opendatakit/javarosa/issues/64. Any chance you can make that happen? A movement on https://github.com/XLSForm/pyxform/issues/113  could also result in us releasing pyxform.

**Comment by lognaturel** [comment]
Thanks so much for pushing on all this! Will aim to do a Validate release in the next few days. @yanokwa does that sound right? I think #113 is going to take a little bit.

**Comment by lognaturel** [comment]
Would be amazing if #137, #128 and #126 could be squeezed in. I need some guidance on approach but am happy to get them done.

If you'd prefer not to delay further, that's fine too!

**Comment by lognaturel** [comment]
Clearly I was too optimistic about adding on that additional functionality! 

I have a pull request for #128 ready. If you have a chance to review that it would be great but if not or it needs a lot of work, it can be pushed back. I'll try to get to the others soon but I don't think they should block a release. There will be a release of ODK Collect on the 30th and it would be great to be able to announce `range` and the few nice incremental improvements to XLSForm at the same time if possible.

**Comment by yanokwa** [comment]
@ukanga @lognaturel I think at this stage, we are letting perfect be the enemy of the good. I think we have enough to do a release of pyxform, so let's do one as soon as possible and then iterate from there...

**Comment by lognaturel** [comment]
Closing in favor of https://forum.opendatakit.org/t/pyxform-release-process/10431 since that seems like a more appropriate place for high-level discussions!
