### ISSUE TITLE
External choices with integers in names/values are converted to decimals

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#123]
If you have an external choice with the name/value of "1", pyxform converts this value to "1.0" in the itemsets.csv. This does not happen with regular choices.

Input
* [numeric.xlsx](https://github.com/XLSForm/pyxform/files/1059737/numeric.xlsx)

Output
* [numeric.xml.txt](https://github.com/XLSForm/pyxform/files/1059739/numeric.xml.txt)
* [itemsets.csv.txt](https://github.com/XLSForm/pyxform/files/1059740/itemsets.csv.txt)

**Comment by phil-wilson** [comment]
@MartijnR Note this breaks cascading selects and/or using pulldata() functions, as the integer being converted to decimal does not match the original value in choices sheet or other csv source.

**Comment by MartijnR** [comment]
Definitely a bug and a serious one.

**Comment by yanokwa** [comment]
@phil-wilson @MartijnR Either of you able to send in a PR?

**Comment by MartijnR** [comment]
No, sorry, I cannot unfortunately.

**Comment by phil-wilson** [comment]
@spatialdude
