### ISSUE TITLE
Add setting for auto-send and auto-delete

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#126]
`orx:auto-send` and `orx:auto-delete` were added as attributes to the `submission` element in opendatakit/xforms-spec#100. Both can be set to either `"true"` or `"false`" and can combine. For example:
`<submission orx:auto-delete="true" orx:auto-send="false">`

It seems that to fit existing XLSForms idioms, each would get its own settings column.

**Comment by lognaturel** [comment]
If I could get a sanity check on the approach I'd be happy to take a stab at this.

**Comment by MartijnR** [comment]
> each would get its own settings column

Makes sense!
