### ISSUE TITLE
Add setting for audit

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#128]
opendatakit/xforms-spec#94

The agreed-upon XForms syntax is:
```xml
<orx:meta>
    <orx:audit/>
</orx:meta>

<bind nodeset="/orx:meta/orx:audit" type="binary"/>
```

For now, including this would mean a csv file with detailed timing information is included with each form submission. In the future, there will also be the option to customize the contents of the csv (e.g. add location information) through attributes.

More about the feature and how it works is at opendatakit/collect#257

I presume this would be an `audit` column in the settings sheet. For now it could just contain yes/no true/false and eventually can have other values as the audit concept is expanded. Alternately the column could be named `audit_type` and currently only accept the value `timing`. 

@MartijnR I bet you have ideas for this.

**Comment by MartijnR** [comment]
Would using the same as `start` and `end` also be workable (so type `audit` in the survey sheet)? Maybe in conjunction with the argument solution we end up after finalizing the discussion in #79 for future audit types?

This may be considered scope creep, and if so we could move it to a separate issue, but it seems like a great opportunity to also _fix_ metadata in pyxform to conform to [our spec](https://opendatakit.github.io/xforms-spec/#metadata) by:

* [ ] not requiring a `name` value (and ignoring it if users do add it)
* [ ] use the **fixed** nodeNames as specified in the spec for the individual meta nodes
* [ ] adding the required namespace on both the meta block and the individual meta nodes
* [ ] make sure `instanceID` is put under the same namespaced meta block
* [ ] don't add a `calculate` attribute on the instanceID bind, but  add  a `preload="uid"` attribute instead (@lognaturel, is ODK Collect ready for this?)

**Comment by lognaturel** [comment]
Oooh, yes, using the same structure as `start` and `end` is perfect. I'm on board with that and agreed that the attributes/properties/parameters column from #79 will be exactly what is needed for audit types.

Some of your other suggestions are covered by #105. Perhaps they should be added to that issue? One thing to note is that JavaRosa will only support using the OpenRosa XForms namespace for meta and its children starting in the next release. It's not clear when Aggregate will be updated by UW. I'm in favor of getting pyxform in line with the spec but I propose waiting a couple of months on those changes so that users have time to update their various tools. It would be disruptive if all of a sudden a bunch of newly-generated forms started failing.

I believe ODK Collect handles `preload="uid"` [here](https://github.com/opendatakit/javarosa/blob/c625845e270eeb1d04c5c0d92fb2f06f2d43196c/src/org/javarosa/core/model/utils/QuestionPreloader.java#L104).

**Comment by MartijnR** [comment]
Ah yes. I'll move them to #105! Waiting a few months is fine (probably also for this issue then)

**Comment by lognaturel** [comment]
😭😭😭 That's right! It seems really unfortunate to have to wait... is it the right thing to do both for this and #105? What has been done in the past with these kinds of breaking changes? Alternately, I suppose this one could be added the "old way" first.

**Comment by lognaturel** [comment]
@MartijnR what do you think about generating it as `audit` without the namespace for now? Then we could find out who is affected by the `orx` addition and plan #105 accordingly as a separate thing.

**Comment by MartijnR** [comment]
yes, alright with me :worried:
