### ISSUE TITLE
Convert files with leading numbers in their name

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#130]
Files with leading numbers in their name error out with `pyxform.errors.PyXFormError: The name '1-basic' is an invalid xml tag. Names must begin with a letter, colon, or underscore, subsequent characters can include numbers, dashes, and periods.`

This is because pyxform uses the name of the file (e.g., basic.xlsx) as the name of the node inside the instance.
```
    <h:title>basic</h:title>
    <model>
      <instance>
        <basic id="basic">
          <note/>
          <my_name/>
```
So when the name of the file starts with 1, the name of the node will start with 1 and that is not valid XML. I'm not sure what the best fix here would be, but some options to consider:
 * Prepend numbers in the node name with _
 * Use fixed name (e.g., ODK Build uses `data`)

**Comment by ukanga** [comment]
I do like the second option, having a fixed name `data`.  Where I have had to change this is when trying to merge data from two different forms with the same fields using ODK Briefcase. I ended up using `find` and `sed` to search and replace node paths to match up.

**Comment by ukanga** [comment]
Looking at https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2json.py#L900 I think this ought to be something determined by the application using this library i.e 
```python
 data = parse_file_to_json(path, default_name='data')
```

Would this work for you?

**Comment by yanokwa** [comment]
My desired outcome is that [xls2xform.py#L18](https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2xform.py#L18) always uses `data` as the default_name. So if you are proposing that, it'd work great for me! 

@MartijnR does that break anything ecosystem wise? Is `data` a reasonable name?

**Comment by MartijnR** [comment]
Yes, it's fine with me. 

The only disadvantage is that we currently have some protection when people try to edit a record in an amended version of the form. Enketo will show an error that the rootnodes are not the same. This is a much-hated message but it's also nice-to-have protection (against server issues when updating a form). So now it will be mostly up to Ona/KoBo to make sure records are edited in the right form @ukanka @dorey!

**Comment by ukanga** [comment]
We do have such a check in Ona for form replacements, so this will simply apply to all new forms when this is implemented.

**Comment by dorey** [comment]
I agree that `<data>` is a good root node name.

**Comment by yanokwa** [comment]
Sounds like we have consensus! 🎉
