### ISSUE TITLE
Add orx:max-pixels attribute for images

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#137]
As described in opendatakit/xforms-spec#79.

The output should be of the structure
`<bind ref="/path/to/node" orx:max-pixels="1024" type="binary"/>`

I'm thinking something like 
```
| survey |        |          |       |                     |
|        | type   |   name   | label | parameters          |
|        | image  | my_image |...    | max-pixels=1024  |
```

**Comment by ukanga** [comment]
Does it mean that any key/value pair in parameters should be added as `orx:[key]`? What should determine if parameters are meant for body attributes or bind attributes or instance attributes? In range, the parameters column was applied as body attributes.

At the moment this can be achieved by a `bind::attribute`,
```
|        | type        | name           | label   | bind::orx:max-pixels    |
```

**Comment by MartijnR** [comment]
To hide this difficulty from the user, I think pyxform should magically put in the right location based on the known parameter name and the question type (and usually also change the user-friendly parameter name into an XForm-friendly attribute name - though not in this case, and add namespaces if required).

**Comment by lognaturel** [comment]
Should have made my thinking more explicit, thanks @MartijnR for filling in the gaps! 

The way I'm thinking about `parameters` is that it's a convenience column that makes it possible to hide XForms details from users a bit more. Unlike `appearances`, values in `parameters` wouldn't be passed through but instead "translated" in some way, as @MartijnR describes. Does that sounds acceptable, @ukanga? Were you thinking about it in a different way?

**Comment by ukanga** [comment]
So far, I want to use `parameters` for external functions e.g `simprints.IDENTIFY(apiToken=XXX)` which applies to a binding. 

I suppose we could leave the choice to the widget to generate the appropriate XML and determine the location of the attribute.

**Comment by lognaturel** [comment]
@ukanga For the Simprints example, are you working with the Simprints folks directly? It looks like @LimaEchoCharlie has a widget implementation over at https://github.com/SimPrints/odk-collect and perhaps it's something that could be coordinated across the ecosystem and go into core. On the XLSForms side, seems it would be nice to use something like `simprints-api-token=XXX` in the `parameters` column and do a translation similar to what I'm suggesting for `orx:max-pixels`. Might be good to discuss in a separate issue and perhaps starting at the XForms level. It looks like the sample widget pulls the API key from a CSV but it would certainly make more sense to specify when defining a form.

**Comment by ukanga** [comment]
Yes, we are discussing on the best way the sim print app can work with ODK Collect with minimal changes to ODK itself, I think once that's clear we can look into how to simplify the XLSForm for the user when defining external apps. We will create an issue as soon as that's clear for discussion.

**Comment by lognaturel** [comment]
That sounds good.

Are you ok with the proposal for `orx:max-pixels`  or would you prefer an alternate approach?

**Comment by MartijnR** [comment]
Yes, I like it.

**Comment by dorey** [comment]
In the JSON representation, it might be easier to describe it like:

```
{
  "type": "image",
  "name": "my_image",
  "label": "my label",
  "max-pixels": 1024
}
```

Because any number of things might feel appropriate to put into a `"parameters"` column.

**Comment by lognaturel** [comment]
@dorey that seems fine to me except perhaps the JSON should also be namespaced so we'd have `orx:max-pixels`. In effect, we'd be agreeing that as far as the XLSForm abstraction is concerned, there's only one thing called `max-pixels` and it is a `parameter` to an `image`. That would translate to the developer-facing JSON and ODK XForms representations that use namespace and a separate attribute/key. That makes it clear from an implementation standpoint that `max-pixels` is custom and places it meaningfully for each representation (on the bind in XML and as its own key in JSON) while hiding those details from users who really don't need to know them.

**Comment by lognaturel** [comment]
@ukanga, @MartijnR any last thoughts on this? I'd like to get it in soon!

**Comment by ukanga** [comment]
Nope, no objections on this.

**Comment by MartijnR** [comment]
Good to go, I think!
