### ISSUE TITLE
Make all column headers case insensitive

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#138]
In https://github.com/XLSForm/pyxform/pull/131#issuecomment-312301325, @ukanga said:
> All column headers tend to be case sensitive in XLSForm.

XLSForm seems very flexible with inputs and I was struck that some column headers were case sensitive. Is there a reason for this? If no, I think we should make them case insensitive!

**Comment by mberg** [comment]
strongly agree unless it's a weird xform thing

**Comment by lognaturel** [comment]
Closed by #141
