### ISSUE TITLE
Show warning when language doesn't include language code

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#143]
In XLSForm/xlsform.github.io#73, @MartijnR describes an agreed-upon format for describing languages in a machine-interpretable way -- `<free text> (<language code>)`.

Show a warning when that format isn't respected. I see two options: just seeing whether the string ends in something like `\([a-zA-Z-]{2,}\)` or actually validate against [IANA subtags](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). I think it would be nice to do a full validation but perhaps that's overreaching.

The warning could say something like `"The language specified doesn't include a machine-readable code as recommended by <link to XLSForm section about the suggested format>."`

**Comment by MartijnR** [comment]
I think adding this warning would be useful. Encouraging users (or form building apps) to add the IANA codes (subtags), will make it possible to match form and UI languages in clients.
