### ISSUE TITLE
Support for a rating appearance type 

### ISSUE THREAD

**Issue by JohnHasthorpe** [XLSForm/pyxform#145]
Suggestion to add support for a **rating** appearance type.

![image](https://user-images.githubusercontent.com/24929507/29391484-0485c464-833b-11e7-9c33-2737260b8454.png)

This would be on the integer question type and would be logically similar to likert. 
However, the requirement to return an integer and have a range of icons highlighted (as apposed to just the one selected) make this distinct.

**Comment by MartijnR** [comment]
+1 for adding this feature.

I wonder if this is perhaps better suited to be implemented as an appearance on the fancy new `range` type.

An issue would be the flexibility with `min`, `max` and `step` in the range type. Here we always want `step` to be 1 and probably `min` to be 0 or 1, right?

If using `range`, should we deal with these min/step restrictions by just letting the widget refuse to instantiate if the parameters deviate (and show a regular range widget instead)?

**Comment by lognaturel** [comment]
Sounds like a good feature and it does indeed seem best connected to `range` in some way.

Any chance you could both look at [this thread](https://forum.opendatakit.org/t/formalizing-process-for-odk-xforms-spec-changes/9377) and comment on your preferred way to make decisions on these kinds of proposals? With some ideas coming in in the XForms spec repo, others in XLSForm spec, others on the ODK forum and yet others here, I think it's really hard for people who want to be involved in the process to follow and for information about new features to flow to all ODK XForms spec implementers. I really think it would be helpful to have one clear process (although you can feel free to disagree there if you don't think that's the case).

**Comment by MartijnR** [comment]
Thanks for the reminder @lognaturel! Sorry, it took so long to respond to that post. I've done that now.

**Comment by JohnHasthorpe** [comment]
Yes a range appearance makes sense and we would be looking at a min of 0 or 1 and a step of 1.
The widget could deal with parameters outside of acceptable ranges (as you describe @MartijnR), and/or we could perform some form of validation.

**Comment by MartijnR** [comment]
Now that range has been added to pyxform in the last release, we can we perhaps close this by agreeing on an appearance name. Shall we use `rating` or move that discussion to the forum?

One thing to discuss here thing: Do we want pyxform to play a role in enforcing the `start` and `step` parameters by showing an error for negative and 0 values for `start` and a `step` value that is not 1?

I don't think pyxform does this kind of validation so far, and it would seem fine to me to let ODK/Enketo Validate deal with this.

**Comment by lognaturel** [comment]
Agreed that validation can be done by clients. I think this has sat for long enough with the option to comment and is non-controversial enough that we can just move forward with `rating`.
