### ISSUE TITLE
Don't use regex to clean up XML

### ISSUE THREAD

**Issue by alxndrsn** [XLSForm/pyxform#150]
`Survey._to_pretty_xml` pretty-prints XML output using a combination of `minidom` and regular expressions.

`minidom` formats the XML a bit, but also introduces some strange whitespace, which the regular expressions then attempt to clean up.  While this is _reasonably_ successful, it's not perfect.  Simpler would be to use a different XML formatter to `minidom` which actually works out of the box.

The in-line TODO suggests checking out PyXML as per http://ronrothman.com/public/leftbraned/xml-dom-minidom-toprettyxml-and-silly-whitespace/#best-solution:
```
from xml.dom.ext import PrettyPrint
from StringIO import StringIO

def toprettyxml_fixed (node, encoding='utf-8'):
    tmpStream = StringIO()
    PrettyPrint(node, stream=tmpStream, encoding=encoding)
    return tmpStream.getvalue()
```

**Comment by batkinson** [comment]
One thing to think about (and test) when changing to a different library is whether its dependencies are able to be embedded in downstream applications successfully.
