### ISSUE TITLE
Default to no pretty print to save space

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#162]
According to https://forum.opendatakit.org/t/-/10712/3, not using pretty print can save more than a megabyte on large forms. 

Pretty print on
```xml
<text id="static_instance-wards-10339">
    <value>Gangare</value>
</text>
```
Pretty print off
```xml
<text id="static_instance-wards-10339"><value>Gangare</value></text>
``` 
I propose we make pretty print off the default behavior because I don't think a lot of people are editing XML forms after the fact.

**Comment by lognaturel** [comment]
This seems reasonable to me. Any reason not to?

**Comment by SLGiHub** [comment]
I agree, Pretty print off would speed up uploads to a server in areas with limited/poor internet
