### ISSUE TITLE
Choices with spaces should prevent XForm creation

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#175]
If you have a space or special character as the name/value of a select option, pyxform should warn you. It does not warn you when there is a choice_filter.

In the case where you don't have a choice_filter, pyxform does warn, but it should instead throw an error and prevent the creation of the XML because if you have a space the value won't be saved (which to me is data loss that a user may not notice).

[test.xlsx](https://github.com/XLSForm/pyxform/files/1752688/test.xlsx)

**Comment by lognaturel** [comment]
How about always stripping spaces from name/value as suggested in #13?

**Comment by yanokwa** [comment]
I'd rather force the user to make that change and do it in a way that makes sense to them (e.g., maybe they want to use hyphens) for their analysis than do it programmatically.

**Comment by ukanga** [comment]
@yanokwa I think the warnings you are talking about are actually generated by ODK_Validate.jar. Are you suggesting we should handle all these in pyxform?


```XML
Warnings:
ODK Validate Warnings:
XForm Parse Warning: select1 question <value>s [za munda] should not contain spaces, and are recommended not to contain apostraphes/quotation marks
    Problem found at nodeset: /html/body/select1[@ref=/test/country_one]/item/value
    With element <value>

XForm Parse Warning: select1 question <value>s [za munda] should not contain spaces, and are recommended not to contain apostraphes/quotation marks
    Problem found at nodeset: /html/body/select1[@ref=/test/country_two]/item/value
    With element <value>

```

**Comment by lognaturel** [comment]
Halting conversion and forcing users to handle the space makes sense. @ukanga can #13 be closed in favor of this one?

**Comment by yanokwa** [comment]
@ukanga Thanks for forcing me to think a bit deeper about this. You are correct that this is not a pyxform bug. 

Spaces in select_one's should be allowed and if they are not persisting data in Collect, then the bug is in Collect.

**Comment by lognaturel** [comment]
Oh dear, I just realized #13 is about stripping leading and trailing space in the column header names which is totally fine and not related.
