### ISSUE TITLE
New Release of Pyxform

### ISSUE THREAD

**Issue by shivareddyiirs** [XLSForm/pyxform#180]
Dear Developers,
I am eager to see new release of pyxform.
I am particularly interested in seeing the #179 in new release so that users my QGIS [plugin](https://github.com/shivareddyiirs/QRealTime/tree/QGIS3) can migrate to QGIS 3 easily.

thanks

**Comment by yanokwa** [comment]
Fixed by 4c2b7f4c1fc7b74c651c86116a0ad19df51d23a9
