### ISSUE TITLE
Use application/* or add gpx and xml media types to file type

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#194]
The file type currently results in the following XForms output:
```
<upload mediatype="text/plain,application/pdf,application/vnd.ms-excel,application/msword,text/richtext,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/zip,application/x-zip,application/x-zip-compressed" ref="...">
```

I see that `application/*` was avoided with the original implementation because of some Chrome issue? https://github.com/XLSForm/pyxform/issues/33#issuecomment-100297975 @MartijnR or @ukanga, perhaps one of you remembers more.

I think it would be ideal if `application/*` could now be used as the default for `file`. If not, then can we add `application/gpx+xml` and `application/xml`?

We could also use the `parameters` column to give the form author more control.

**Comment by MartijnR** [comment]
I recently tried to look into what that 'Chrome issue' was. Unfortunately, I could not find anything about it. So we could leave that out of consideration, I think unless you remember @ukanga (it was an issue Ona reported I believe).

The other reason for specifying file types explicitly was to exclude executables. If that makes sense, we could add file types as needed. Not sure if it makes sense though, since I've since then learned you can bypass the picker formats so the protection is weak.

**Comment by lognaturel** [comment]
> Not sure if it makes sense though, since I've since then learned you can bypass the picker formats so the protection is weak.

Agreed it's not all that strong of protection in a browser. And I think in general enumerators can be trusted.

My preference would be to use `application/*` as the default now and start the discussion on an acceptable `parameters` column format. A very simple thing we could do is if the `parameters` column includes a `mediatype` key, use whatever is in the value as the XForms `upload`'s value. This does require the user to look up mime types but it gives maximum flexibility without much effort.

**Comment by MartijnR** [comment]
Yes, `application/*` works for me for type=file (and combining this issue with #101).

Not sure if we need to use the parameters column for advanced mediatype tweaks, but no objection to it either. The `accept` attribute can currently already be overridden by `body::accept` ([example](https://docs.google.com/spreadsheets/d/1QBC_54jSYGA9FQD0M9M-nJM_JOmpRnYrbN9Cew-o7tc/edit?usp=sharing)). This is how some users are today using `application/*` already.

If a specific media type is considered common, I'd be in favor of adding a type for it, such as type=pdf.

**Comment by ukanga** [comment]
I cannot trace that conversation, I am okay with `application/*`. I see we use `audio/*`, `image/*`, and `video/*` already.

**Comment by ukanga** [comment]
In relation to use the `parameters` column, not so sure about that, currently, as @MartijnR had suggested we could use `body::mediatype` with the value `application/*` to achieve the same effect.

**Comment by lognaturel** [comment]
Ahh, I always forget about the `body::`/`bind::` columns. That's perfect.

**Comment by MartijnR** [comment]
Just a little warning, I would always advice users to use `body::accept` (and not `body::mediatype`), because the accept attribute can take multiple mime types according to https://opendatakit.github.io/xforms-spec/#body-attributes.
