### ISSUE TITLE
Forms with choice filters crash at has_external_choices

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#20]
If a form has a choice_filter, the check for has_external_choices fails with 

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyxform/xls2xform.py", line 65, in <module>
    warnings = xls2xform_convert(args.path_to_XLSForm, args.output_path)
  File "/usr/local/lib/python2.7/site-packages/pyxform/xls2xform.py", line 24, in xls2xform_convert
    if has_external_choices(json_survey):
  File "/usr/local/lib/python2.7/site-packages/pyxform/utils.py", line 115, in has_external_choices
    elif has_external_choices(v):
  File "/usr/local/lib/python2.7/site-packages/pyxform/utils.py", line 113, in has_external_choices
    if k == u"type" and v.startswith(u"select one external"):
AttributeError: 'list' object has no attribute 'startswith'
```

The problem is that choices are also represented as k=type. Easiest fix is to make sure v is a list. 

```python
if k == u"type" and isinstance(v,basestring) and v.startswith(u"select one external"):
```

**Comment by ukanga** [comment]
I think we have this fixed on master already, see https://github.com/XLSForm/pyxform/commit/b7b7ecb10e86bcb3673afe5136988c10c0625869.

**Comment by yanokwa** [comment]
Agreed. When are you planning on releasing a new version? I try not to build around master.

**Comment by ukanga** [comment]
I haven't had much time to look at issues and get some of them closed and https://github.com/XLSForm/pyxform/compare/v0.9.22...master does not seem like much to warrant a release. Maybe time it with the next ODK Validate release. But if there is much demand I could do one with the current master as is.

**Comment by yanokwa** [comment]
Nah, don't worry about it. I'll just do a release on master every few months.
