### ISSUE TITLE
Add support for translating or_other?

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#218]
As noted at https://forum.opendatakit.org/t/translation-for-or-other/14161, if you have an or_other question, there's no way to localize the "other" text. 

If there isn't an easy way to do this (I can't think of it), maybe the solution here is to describe this limitation at https://github.com/XLSForm/xlsform.github.io,

**Comment by ukanga** [comment]
I don't this is supported yet in XLSForm. I will agree with you on making an update of the limitation.

I propose we add additional columns into the xlsform, `label_other` and `label_other_specify` or something simpler `other` and `other_specify`.

| survey  |                                  |          |                |                |                |                |                        |                        |
|---------|----------------------------------|----------|----------------|----------------|----------------|----------------|------------------------|------------------------|
|         | type                             | name     | label::English | label::Italian | other::English | other::Italian | specify_other::English | specify_other::Italian |
|         | select_multiple mylist or_other  | rank     | Rank           | Rango          |  Other         | Altro          | Specify other          | Specificare altro      |
| choices |                                  |          |                |                |
|        | list_name                        | name     | label::English | label::Italian |
|        | mylist                           | a        | A              |  AA            |
|        | mylist                           | b        | B              |  BB            |

**Comment by MartijnR** [comment]
I wonder if this is still easier than letting users create a separate 'other' question manually if translations are required (and providing an example for this on xlsform.gihub.io).

**Comment by yanokwa** [comment]
I hesitate at adding more columns. Truth be told, I've never loved the `or_other` syntax because it ends up being restrictive in other ways (e.g., maybe you want to use a number as a value instead of 'other'). Would it be crazy to just point out this limitation and maybe move to deprecate `or_other`?

**Comment by craigappl** [comment]
Notes from breakout session:
### Decision
1) We do not need to do this. We will close this issue.
2) This needs to be an issue in the xform spec.

**Comment by lognaturel** [comment]
Forum post: https://forum.opendatakit.org/t/allow-custom-choices-for-selects-that-get-saved-to-the-same-field/22788

ODK XForms spec issue: https://github.com/opendatakit/xforms-spec/issues/249
