### ISSUE TITLE
Validate fails when a guidance hint is specified without a regular hint

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#225]
I see there are several tests for this, that pass, so I'm not sure what's going on, but the attached form will not convert with following error:

```
Error: b"ODK Validate Errors:\n>> XForm is invalid. See above for the errors.\norg.javarosa.xform.parse.XFormParseException: <hint> '${b}:hint': text is not localizable for default locale [default]!\n\nResult: Invalid"
```

[guidance.xlsx.txt](https://github.com/XLSForm/pyxform/files/2380307/guidance.xlsx.txt)

**Comment by lognaturel** [comment]
I forgot to run the tests with Validate on. Should be able to push a Validate update soon. In the mean time, converting without validating works.

**Comment by MartijnR** [comment]
Ah right! Thanks!

**Comment by MartijnR** [comment]
FYI @aurdipas
