### ISSUE TITLE
output_path should default to path/to/file

### ISSUE THREAD

**Issue by joeflack4** [XLSForm/pyxform#227]
## Expected behavior
When trying to convert a file, if output_path is not supplied, output_path should automatically be set to the same directory of the file being converted, using the same file name (other than changing the extension to .xml).

**Example**
`path/to/myFile.xls` --> `path/to/myFile.xml`

## Actual behavior
output_path is a required argument

**Comment by MartijnR** [comment]
> sans extensions

changed to .xml right?

**Comment by joeflack4** [comment]
Yep! I updated my original post to be more clear, thanks.
