### ISSUE TITLE
Should not evaluate non-xlsform standard sheets

### ISSUE THREAD

**Issue by joeflack4** [XLSForm/pyxform#229]
## Expected behavior
Pyxform should ignore any sheets that are not part of typical xlsform spec, e.g. "survey, choices, external_choices, settings".

## Actual behavior
There are edge cases in which unexpected behavior can occur due to the presence of non typical xlsform spec sheets. For an example, see this issue: https://github.com/XLSForm/pyxform/issues/228

**Comment by ukanga** [comment]
@joeflack4 If we address this issue should we at all address #228 considering the error occurs on a non-standard sheet?

**Comment by joeflack4** [comment]
@ukanga Hello~. I leave it up to you. But to be honest, issue #228 can still occur even for standard XLSForm worksheets. So IMO, I'd leave it open.
