### ISSUE TITLE
PYXForm should fail if a choiceList has two or more choices sharing the same value.

### ISSUE THREAD

**Issue by mitchellsundt** [XLSForm/pyxform#23]
When processing the XLSX file, it would be helpful if the conversion failed if a user has entered two rows in the choices sheet for a given choice list that have the same value. 

The use case is someone copy-and-pasting a series of answers:

listA  val1 Yes
listA  val2 No
listA  val2 Maybe

and not noticing that val2 is repeated twice (Maybe should be val3).

If we want to support the current mechanism where this is allowed, we should probably have 
a settings tab flag that allows for duplicated choice values.

**Comment by dorey** [comment]
At one point we did something like this in koboform but there were cases where people want to be able to have multiple labels represented as the same value, and now I think a rule like this would be restrictive. Would it help to pass back a warning if duplicate values are used?

**Comment by mitchellsundt** [comment]
Yes, if there is any way to get a warning back, that would be great. 

I haven't been following how pyxform deals with external itemsets. If it wraps everything into a single zip, if the zip contained a warnings file, that would, I think, be helpful.  Or if it produces multiple files, adding a warnings file for these sorts of things would be useful.

**Comment by dorey** [comment]
This is coming back and leading to a number of reported issues when users accidentally make bad forms.

I suggest we have a settings that protects the cases where duplicate choices are intended, and then we automatically reject forms with duplicate choice values.

```
# survey

...

# choices (example where duplicate choice values are desired)

| list_name |    value     |      label      |
|-----------|--------------|-----------------|
| age       | out_of_range | 0-20 years old  |
| age       | out_of_range | 21-40 years old |
| age       | out_of_range | 41-60 years old |
| age       | in_range     | 61-80 years old |
| age       | out_of_range | 80+ years old   |

# settings

| allow_choice_duplicates |
|-------------------------|
| Yes                     |
```

I'm proposing that if this setting is not present, this form would get rejected.
