### ISSUE TITLE
Tests and Tests_v1 exist without docs as to why

### ISSUE THREAD

**Issue by KeynesYouDigIt** [XLSForm/pyxform#230]
WHy have both?

**Comment by yanokwa** [comment]
Now that I've written a test, I wonder if we should rename those folders to make this self-documenting. 
* Tests -> tests_legacy
* Tests_v1 -> tests

**Comment by lindsay-stevens** [comment]
Closing this since as of #562, `./pyxform/tests` and `./pyxform/tests_v1` are now in `./tests`; and a [readme section](https://github.com/XLSForm/pyxform/blob/master/README.rst#writing-tests) was added to document how/where to write tests.
