### ISSUE TITLE
Duplicate names for questions across levels

### ISSUE THREAD

**Issue by ajaydivakaran** [XLSForm/pyxform#24]
Hi,

What is the rationale to allow duplicate names for questions across levels? 
e.g a date question at the top level can have the same name as a date question within a group.

Is this something that will be restricted sometime in the future?

**Comment by yogeshsr** [comment]
I guess the names are actually not duplicate. See the nodeset below, when xlxform is converted to xform.

`<bind nodeset="/toplevelformname/date" required="true()" type="string"/>`
`<bind nodeset="/toplevelformname/groupname/date" required="true()" type="string"/>`
