### ISSUE TITLE
Remove default geopoint hint

### ISSUE THREAD

**Issue by tiritea** [XLSForm/pyxform#241]
## Steps to Reproduce

    …add geopoint question to form but dont add any hint
    …preview form in Enketo
    …

## Expected behavior

no hint

## Actual behavior

see default hint "GPS coordinates can only be collected when outside."

## Additional details

Always displaying a default hint is not really appropriate, and indeed this particular hint is not even correct (it is quite possible to get a GPS fix inside a house or building)

I cant find anything in the actual code to remove this using a PR. I suspect the hint is getting copied out of one of the template spreadsheets (base.xls or all.xls) and used to initialize geopoint hint in any new form definition otherwise lacking a corresponding user-defined hint.

In general, I dont believe the pyxfom tool should be adding *any* new semantic content into a form (even if well intentioned...). If the form writer wants a suitable hint in their form then it is their responsibility to explicitly define one. And if they dont want a hint then it should be possible not to have one [sic].

**Comment by lincmba** [comment]
This is no longer an issue in Pyxform. 
It was addressed in this PR #67
