### ISSUE TITLE
Bug - choice_filter inside repeat can result in errors

### ISSUE THREAD

**Issue by joeflack4** [XLSForm/pyxform#244]
## Description
If using `choice_filter` inside a repeat and referring to a node within a / that repeat, the following type of error message can appear.

![screenshot_20181201-210910](https://user-images.githubusercontent.com/13045020/49335701-a674d280-f5c0-11e8-82ab-7bea3046853e.png)

## Additional information
The workaround for this currently is to find the choice_filter usage inside the XML and make a replacement. For example, if converting _attachment 1_  into XML, you would then make the following replacement.

**Find:**
`filter_list= /KAP/caregiverKAP/region_born`

**Replace:**
Older versions / forks of ODK Collect (i.e. JHU Collect)
`filter_list= current()/region_born`
Current version of ODK Collect
`filter_list= current()/../region_born`

---

**Attachments**
1. [Demo_excerpt_from_KAP_XLSForm-v4-jef.xlsx](https://github.com/XLSForm/pyxform/files/2636593/Demo_excerpt_from_KAP_XLSForm-v4-jef.xlsx)

**Comment by ukanga** [comment]
This seems like it is going to be addressed by #187. Does that PR address your use case?

**Comment by lognaturel** [comment]
@joeflack4 Can you please confirm that this is fixed in the latest releases of the form converters?

**Comment by ukanga** [comment]
@joeflack4  Please reopen if this is still an issue.
