### ISSUE TITLE
Performance regression in 0.12

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#247]
xls2xform 0.12.0 takes *a lot* longer to convert to XML than 0.11.5.  

I noticed this problem on [this forum topic](https://forum.opendatakit.org/t/502-bad-gateway-error-while-using-the-xlsform-online/16866) and to investigate, I set up a local [xlsform-server](https://github.com/opendatakit/xlsform-server) and used the [soar.xlsx.zip form](https://github.com/XLSForm/pyxform/files/2717811/soar.xlsx.zip).

I then ran a local conversion
```
cd /home/ubuntu/xlsform/xlsform_env/bin/
time ./xls2xform /home/vagrant/test.xlsx /tmp/test.xml
```

On pyxform 0.11.5, it took about 1.4 seconds (multiple runs)
On pyxform 0.12.0, it took about 23 seconds (multiple runs)

On a very fast local machine, this change isn't that noticeable (it takes 2 seconds), but on a single-core cloud VPS like the one that runs http://opendatakit.org/xlsform, it pegs the CPU for minutes at a time and results in gateway timeouts.

My guess is that this regression happened with https://github.com/XLSForm/pyxform/pull/187.

@MartijnR @ukanga can you reproduce?

**Comment by ukanga** [comment]
Let me look into it.
