### ISSUE TITLE
Support XForms OSM Upload Media Type

### ISSUE THREAD

**Issue by ukanga** [XLSForm/pyxform#25]
- documentation: https://github.com/AmericanRedCross/openmapkit/wiki/XForms-OSM-Upload-Media-Type
- [example xlsform](https://docs.google.com/spreadsheets/d/1TZOgkywU2oTy5GuNcO5-GzX7eZRcxzhUx-7VWvMR3mk/edit?usp=sharing)

**Comment by biplovbhandari** [comment]
Hi ukanga, the example xlsform works in ONA or not?
