### ISSUE TITLE
Support python 3 only as python 2 support is coming to and end in 2020

### ISSUE THREAD

**Issue by bmarika** [XLSForm/pyxform#256]

**Comment by code-player** [comment]
Hey, I would like to work on this issue. Here is the list of plans that I wish to implement
1. Add checks to prevent any code executions on python2.
2. Remove python2 from all CI-CD platforms.

Please provide your feedback.

**Comment by jnm** [comment]
There are definitely Python 2 tools using this library (I help maintain one of them). What's the motivation for discontinuing Python 2 support prior to 2020? Are there new features in the language that you're hoping to use now?

**Comment by code-player** [comment]
> What's the motivation for discontinuing Python 2 support prior to 2020?

By starting to discontinue Python2 now will give us sufficient time to all types of tests for regression than doing it at the last minute.
 
> Are there new features in the language that you're hoping to use now?

For now, I'll start by just running everything on Python3 only, which appears to be working. There are some problems with nosetests, which I would like to start with. 

If you want to fix some issues with higher priority, I would be happy to start with them too.

**Comment by jnm** [comment]
If there are issues with Python 3 tests or compatibility, then I'd definitely support you fixing them. I thought that all Travis CI tests (which use nose) were passing on the `master` branch for Python 3.5, 3.4, and 2.7, but please correct me if I'm wrong. Thank you for looking into this.

Just to clarify: there's no "last minute" for us to "Add checks to prevent any code executions on python2." We can support Python 2 for as long as we want. If, after official support for Python 2 ends in 2020, supporting Python 2 comes at the detriment of Python 3, then I would support removing Python 2 compatibility.

**Comment by code-player** [comment]
> If there are issues with Python 3 tests or compatibility, then I'd definitely support you fixing them. I thought that all Travis CI tests (which use nose) were passing on the `master` branch for Python 3.5, 3.4, and 2.7, but please correct me if I'm wrong. Thank you for looking into this.

I was running the nosetests locally on python3, some 4 tests happen to fail. I'll see and get the proper tracebacks which will help debugging the failed tests.

**Comment by KeynesYouDigIt** [comment]
Good to see this issue is being addressed, if someone runs out of time/bandwidth LMK and I can take it over. Note that Circle files show the tests commands that need to pass now, as well as appveyor (travis is gone right? dont see it running in any current PRs and the config is gone)

**Comment by lindsay-stevens** [comment]
Addressed in https://github.com/XLSForm/pyxform/pull/408 (Dec 2019).
