### ISSUE TITLE
Remove Appveyor, replace Travis with CircleCI

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#262]
My guess is that Appveyor was used to verify Windows support, but pyxform is pretty platform agnostic, so I don't think think it's needed.

Travis works fine, but the ODK tools all use CircleCI and I think some consistency there would be nice. One tricky thing here will be running the tests on the various versions of Python.

**Comment by ukanga** [comment]
In terms of making pyxform ODK tools compliant I agree. However, where windows is concerned, we introduced AppVeyor after conversations in this PR https://github.com/XLSForm/pyxform/pull/116 necessitated it. I deploy pyxform only on Linux environments but that is not the case for all pyxform users. Can this be reconsidered?

**Comment by yanokwa** [comment]
Seems like the core of the issue is the install (See https://github.com/XLSForm/pyxform/pull/63#issue-68332623). Agreed that we should keep Appveyor, but maybe replace Travis with CircleCI? I've updated the PR so you see what that looks like.

**Comment by ukanga** [comment]
> ... replace Travis with CircleCI?

Ok with me.
