### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Makdavy1** [XLSForm/pyxform#278]
I am getting this error on KoboCollect. What should I do?

![image](https://user-images.githubusercontent.com/34172128/54962032-45f51100-4f74-11e9-8f0f-62dae4849056.png)

**Comment by jnm** [comment]
Hi @Makdavy1, that's not KoboCollect, that's a KoBoToolbox preview that would be generated by Enketo Express. Could you please make sure that your XLSForm is valid by checking it with http://opendatakit.org/xlsform/, or, if you used the graphical form builder to create your form, open an issue at https://github.com/kobotoolbox/kpi?

**Comment by Makdavy1** [comment]
Thank you @jnm. Solved already

**Comment by jnm** [comment]
Great! How'd you figure it out, though, for the benefit of future searchers?

Also, for indexing purposes, the error in the screenshot is `Parameters must include randomize=true to use a seed.`

**Comment by Makdavy1** [comment]
I downloaded it in XLS format. Then Deleted a statement "Randomize=false" as seen on the screenshot 
![image](https://user-images.githubusercontent.com/34172128/55052467-26401480-506a-11e9-9ead-aa4ef4d5c076.png)
