### ISSUE TITLE
Don't generate itext block if only one language is defined

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#285]
The `itext` block can include translations for form elements (see [spec](https://opendatakit.github.io/xforms-spec/#languages)). `pyxform` always adds this level of indirection for cascading selects, even if the XLSForm only defines labels/hints for a single language. This isn't a big deal for small secondary instances but can make the XML much bigger for large ones.

Related to #32 and might be good to address while in the same brain space.

**Comment by lognaturel** [comment]
See [nigeria_wards_internal.xml.txt](https://github.com/XLSForm/pyxform/files/3065921/nigeria_wards_internal.xml.txt) and [nigeria_wards_internal_simplified.xml.txt](https://github.com/XLSForm/pyxform/files/3065923/nigeria_wards_internal_simplified.xml.txt) for what I'm talking about. File size goes from 4.6mb to 3mb.

**Comment by nribeka** [comment]
Checking this one along while waiting for PR review.

**Comment by lognaturel** [comment]
@nribeka This is a really good one to look into. Please ask if you have any questions about the problem or intended behavior.

**Comment by nribeka** [comment]
@lognaturel is there a place where i can get the xls for the form?

From your description and looking at the xml, the idea is to not use the translation field when there's only one language, right? It should inline it instead of separating it. This is only true when the survey have one language only, right?

**Comment by lognaturel** [comment]
Simple example: [XLSForm](https://docs.google.com/spreadsheets/d/1N_wZFefDp1hgOzHdpGyLsdKq32eUralqVz6YjAdpSL4/edit#gid=826818009),[XForm](https://github.com/XLSForm/pyxform/files/3650459/choice-lists-no-translations.xml.txt)

Note that the static choice list uses literal label text which is what is expected. When I force a dynamic choice list by using a choice filter is where the problem occurs.

What we'd like:
```
<instance id="choices">
	<root>
		<item>
			<label>Choice 1</label>
			<value>choice 1</value>
		</item>
		<item>
			<label>Choice 2</label>
			<value>choice 2</value>
		</item>
		<item>
			<label>Choice 3</label>
			<value>choice 3</value>
		</item>
		<item>
			<label>Choice 4</label>
			<value>choice 4</value>
		</item>
		<item>
			<label>Choice 5</label>
			<value>choice 5</value>
		</item>
		<item>
			<label>Choice 6</label>
			<value>choice 6</value>
		</item>
	</root>
</instance>
```

Note that the `itemset` declaration will also need to change:
```
<itemset nodeset="instance('choices')/root/item[name != '']">
   <value ref="name"/>
   <label ref="label"/>
</itemset>
```

**Comment by nribeka** [comment]
@lognaturel,

Another approach would be:
• Add new field in the survey object when creating survey object from the json.
• Use that field (in favor of checking the multi_language all the time) when creating each section.
Thoughts?
The above draft PR obviously break existing tests that have reference to the <itext> field. I'm gonna change the expected output xml files if that's ok?
