### ISSUE TITLE
Remove dummy instance content formerly used to force validation to pass

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#286]
#104 added dummy elements to external instance declarations to get by Validate. That means either clients or humans need to remove those elements to actually get generated forms to work with external files.

For example, for the form in issue #87, instance declarations look like:
```xml
<instance id="states" src="jr://file-csv/states.csv">
    <root>
        <item>
            <name>_</name>
            <label>_</label>
        </item>
    </root>
</instance>
```

Instead, they should look like:
```xml
<instance id="states" src="jr://file-csv/states.csv" />
```

This should be the case for both csv and xml external files.

Generated forms without those dummy elements should now pass Validate and there should be a test added to demonstrate this.

**Comment by MartijnR** [comment]
Would be great to remove this!

**Comment by KeynesYouDigIt** [comment]
I should be able to take this on. Is this what we are talking about when we refer to "external instance" functionality? http://xlsform.org/en/#external-xml-data

**Comment by KeynesYouDigIt** [comment]
When I remove the dummy nodes, the form is now considered invalid by the pyxform validator. Is that cause the validator itself needs to change or because ive sliced out too much?

**Comment by KeynesYouDigIt** [comment]
Validation seems to be implying its the later ```*** pyxform.validators.odk_validate.ODKValidateError: b"ODK Validate Errors:\n>> XForm is invalid. See above for the errors.\norg.javarosa.xform.parse.XFormParseException: <label> node for itemset doesn't exist! [instance(cities)/root/item/label]\n\nResult: Invalid"
```

**Comment by KeynesYouDigIt** [comment]
so this test passes, but if I switch Run ODK validate to True it keeps throwing the same error. Is this form not valid or is the validator outdated? like, does the validator need to get fixed too? hope that question isnt too dumb still learning :/

```python
    def test_external_csv_instances(self):
        # re: https://github.com/XLSForm/pyxform/issues/30
        self.assertPyxformXform(
            name="ecsv",
            md="""
            | survey |                                              |                |                |
            |        | type                                         | name           | label          |
            |        | select_one_from_file cities.csv              | city           | City           |
            |        | select_multiple_from_file neighbourhoods.csv | neighbourhoods | Neighbourhoods |
            """,  # noqa
            xml__contains=[
                """<instance id="cities" src="jr://file-csv/cities.csv"/>""",
                '<select1 ref="/ecsv/city">',
                '<itemset nodeset="instance(\'cities\')/root/item">',
                """<instance id="neighbourhoods" src="jr://file-csv/neighbourhoods.csv"/>""",  # noqa
                '<select ref="/ecsv/neighbourhoods">',
                '<itemset nodeset="instance(\'neighbourhoods\')/root/item">',
            ],
            run_odk_validate=False,
        ) ```

**Comment by KeynesYouDigIt** [comment]
@MartijnR @lognaturel bump. LMK if I am way off track here and I can refocus my efforts

**Comment by MartijnR** [comment]
Thanks for taking this on @KeynesYouDigIt! You probably don't need this anymore, but this is the XForms reference: https://opendatakit.github.io/xforms-spec/#secondary-instances---external

It does seem like ODK Validate may need to be updated. I see pyxform currently has 1.11.0. @lognaturel , should this wait for next Validate release?
