### ISSUE TITLE
Discussion: 'value' instead of 'name' in the choices sheet

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#29]
Leave 'name' as alias for 'value' but change documentation to 'value'.

I think this is more intuitive for end users.

What do you think?

**Comment by ukanga** [comment]
+1 seems ok to me

**Comment by MartijnR** [comment]
fixed by https://github.com/XLSForm/pyxform/commit/1192bb0acc6e15de831c017cf78a4bd8cc642340, right?

**Comment by ukanga** [comment]
Yes, it is fixed by #55.
