### ISSUE TITLE
Resolve field references in attributes for upload questions

### ISSUE THREAD

**Issue by tedrick** [XLSForm/pyxform#292]
The UploadQuestion type, unlike most others, does not currently resolve field references in attributes.  With Survey123, we are adding generic `esri::bind:parameters` and `esri::body:parameters` to cover features out of scope for XLSForm; the `body` parameter needs xpath value insertion.

**Comment by tedrick** [comment]
Given the time that's elapsed, I needed to reset the fix and have submitted #386.  It's failing the CI test with regard to proper formatting, but the error is not helpful to resolve.

**Comment by lognaturel** [comment]
Closed in #386
