### ISSUE TITLE
If there's only one sheet, use that one as the survey sheet

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#296]
I often forget to explicitly name my sheet `survey`. If there's only one sheet, I believe `pyxform` should be able to try using that one as the `survey` sheet.

**Comment by nribeka** [comment]
If anyone interested in this, I started a PR: https://github.com/XLSForm/pyxform/pull/384.

This seems to be working ok when I try them locally.

**Comment by lognaturel** [comment]
Yay! I still generally forget to name my sheet when I only have a survey sheet.

I marked the issue as `needs discussion` because I'm not seeing any risk in this change but I could very easily be missing something (as I did with 0 vs 1 repeat by default). @ukanga and @MartijnR?

**Comment by ukanga** [comment]
Could this be encouraging loose conformance to the XLSForm standard - especially for new users? Would it warrant us to start thinking about being strict or loose with rules?

**Comment by qlands** [comment]
I would not implements this and enforce users to some sort of standards. With the documentation available users can and learn how to make an ODK Form using XLS. I indicated the same for other bits in  #279 .

**Comment by lognaturel** [comment]
I do generally prefer a single standard for names like types and certainly agree that the aliases highlighted in #279 are a problem.

I see the single-sheet case, I see it as more of a fallback than an alias.  I agree that the `survey` sheet should have to be called `survey` and that the `choices` sheet should have to be called `choices` rather than having aliases for those. But defaulting a single sheet to `survey` doesn't seem dangerous to me.

That said, I also understand that I'm particularly likely to run into this problem because I build lots of small sample forms so perhaps this is not a common user problem.

If @ukanga, @qlands and @MartijnR are all against this, let's close.

**Comment by MartijnR** [comment]
Sorry, somehow my response yesterday didn't get posted or disappeared. I was in favor of this feature yesterday (and also create lots of test forms).

Though @ukanga and @qlands comments  make sense as well. I have found that I usually end up regretting adding flexibility.

So I'm in the middle now with a useless vote. 👍 👎

**Comment by qlands** [comment]
:-1:

**Comment by lognaturel** [comment]
> I usually end up regretting adding flexibility.

Agreed. I don’t see this as added flexibility, though, but as filling in a blank when there’s only one logical intent. 

The user either has specified a form with a single sheet where that sheet truly attempts to be a survey sheet. If pyxform assumes it’s the survey sheet, the user will get their converted form or a useful error message to make progress. If the user is trying to convert some random single-sheet spreadsheet, they’ll get an error about missing essential columns which is the real problem with their spreadsheet (not that there’s no sheet names survey). 

But anyway, ball is now In your court, @ukanga! 🏀

**Comment by ukanga** [comment]
Low barrier to entry I suppose I will be a :+1: then.
