### ISSUE TITLE
Add support for ODK Length

### ISSUE THREAD

**Issue by mberg** [XLSForm/pyxform#3]
In ODK Aggregate 1.x, you can supply an attribute to the <bind /> to specify the maximum number of characters used to store a string field; by default, the datastore layer limits strings to 255 characters or less. If a submission has data beyond this length, it is silently truncated upon submission.

Specifying a value less than 255 can significantly improve the storage efficiency of the database layer. You can also specify a value greater than 255, up to a maximum of about 16000 UTF-8 characters. The higher you set this value, the worse the storage efficiency within the datastore.

To set the string length:

In the header of the form definition, add a xmlns alias for odk (shown added as the last xmlns alias at the bottom of the tag):

<?xml version="1.0"?><h:html xmlns="http://www.w3.org/2002/xforms"
        xmlns:h="http://www.w3.org/1999/xhtml"
        xmlns:ev="http://www.w3.org/2001/xml-events"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:jr="http://openrosa.org/javarosa"
        xmlns:odk="http://www.opendatakit.org/xforms" ><h:head>
Then, in the bind, you can define an odk:length attribute to specify the length of a string field. Length can be specified for barcode, select1 and string fields. Multi-selects (select) fields have a 255 character maximum length for each selection value (and selection values must not contain whitespace); there are no limits to the number of choices that may be selected within a multi-select.

<bind nodeset="/nm/repeat_observation/notes" type="string" odk:length="600"/>

**Comment by lindsay-stevens** [comment]
Seems to have been fixed in #172 (previously #165). @Archaejohn could you please confirm? If it is the same we can close this issue.
