### ISSUE TITLE
Add support for external instances

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#30]
[earlier discussion on ODK dev forum](https://groups.google.com/forum/#!topic/opendatakit-developers/9_VZoe7crVY)

* Support for both *select_one_from_file \[FILENAME\]* and *select_multiple_from_file \[FILENAME\]* 
* The above types always create regular `<select>` or `<select1>` with a regular `<itemset>` and always add a single `<instance id="" src="" />` to the model (unless that instance with that id already exists).
* Filenames can have either .csv or .xml extensions.
* instance `id` attribute = lowercased filename minus the extension: countries.csv => `<instance id="countries">`
* instance `src` attribute for XML sources gets `jr://file/` prefix and for CSV sources gets `jr://file-csv/` prefix (similar to jr://image, jr://video and jr://audio).
* the label ref of an itemset is always `ref="label"` because itext references couldn't work.

#### 1a. XLSForm input (CSV file, no choice filter):

| type  | name   | label | choice_filter
|-------|--------|-------|-------------------
| select_one_from_file countries.csv | country | Pick one country |

#### 1b. XForm output:

Very similar to a regular select_one with choice filter (but in this case the choice filter is empty)

```xml
<model>
    <instance>
        ....
    </instance>
    <instance id="cities" src="jr://file-csv/cities.csv" />
</model>
<h:body>
    <select1 ref="/myform/country">
        <label>Country</label>
        <itemset nodeset="instance('countries')/root/item">
            <value ref="name"/>
            <label ref="label"/>
        </itemset>
    </select1>
</h:body>

```

#### 2a. XLSForm input (XML file, no choice filter):

| type  | name   | label | choice_filter
|-------|--------|-------|-------------------
| select_one_from_file countries.xml | country | Pick one country | 

#### 2b. XForm output:

_Exactly the same syntax as used by CommCare for their many XML external instances_

```xml
<model>
    <instance>
        ....
    </instance>
    <instance id="cities" src="jr://file/cities.xml" />
</model>
<h:body>
    <select1 ref="/myform/country">
        <label>Country</label>
        <itemset nodeset="instance('countries')/root/item">
            <value ref="name"/>
            <label ref="label"/>
        </itemset>
    </select1>
</h:body>

```

#### 3a. XLSForm input (CSV file, with choice filter):

| type  | name   | label | choice_filter
|-------|--------|-------|-------------------
| select_multiple_from_file cities.csv | city | Pick some cities | country = ${country}

#### 3b. XForm output:

```xml
<model>
    <instance>
        ....
    </instance>
    <instance id="cities" src="jr://file-csv/cities.csv" />
</model>
<h:body>
    <select ref="/myform/country">
        <label>Country</label>
        <itemset nodeset="instance('cities')/root/item[country= /myform/country ]">
            <value ref="name"/>
            <label ref="label"/>
        </itemset>
    </select>
</h:body>
```

Notes:

* this feature is not compatible with ODK Collect (and vice versa select_external and search are not compatible with Enketo)
* the external data referred to in an XLSForm needs to always have a label column (that's an XLSForm restriction) 
* csv column headers may not contain a colon (this not relevant to Pyxform but to the xlsform.org documentation)
* these XForms do not pass ODK Validate validation (I suspect it checks whether itemset nodeset paths exist), so to use this feature ODK Validate would have to be switched off or tweaked so it bypasses checks for paths that refer to external instances (i.e. that refer to instance(ID)/path/to/node when the targeted instance has a `src` attribute)

**Comment by ukanga** [comment]
Any chance this will be added to javarosa/odk validate/odk collect family?

**Comment by MartijnR** [comment]
Hopefully. Otherwise we need to go ahead with building a new [validator based around's enketo's XPath evaluator](https://github.com/enketo/enketo-validate/issues/1). I know Dimagi is using external XML instances a lot already (same as above). Not sure what validator they use.

The feature is has now been added to Enketo Express.

**Comment by mberg** [comment]
Martijn are you following the approach dimagi is using?  Do they have their
own version of javarosa to support this?

**Comment by MartijnR** [comment]
Yes, same approach. No re-inventing of any wheels. I just added CSV support in addition to XML. Dimagi has their own version of Javarosa that supports XML external instances as above.

**Comment by dorey** [comment]
:+1: for referencing the URL of the external itemset from within the XForm.

**Comment by MartijnR** [comment]
This opens the way for some exciting future possibilities, because the URL posted in the /xFormsManifest could be a dynamic document. E.g. a dynamically created XML (or CSV :-1: ) Document.... It could be external to KoBo/Ona too.

You could e.g. create a service that dynamically creates a document based on another survey or earlier responses to the same survey.

**Comment by mberg** [comment]
Is this working?

**Comment by MartijnR** [comment]
In Enketo Express it is working, yes.

**Comment by mberg** [comment]
Awesome

**Comment by MartijnR** [comment]
One way around ODK Validate is to add dummy content to the external instance. Instead of:

```xml
<instance id="cities" src="jr://file/cities.xml" />
```

we do:
```xml
<instance id="cities" src="jr://file/cities.xml" >
    <root>
        <item>
              <name/>
              <label/>
        </item>
    </root>
</instance>
```

It's just a temporary dirty trick to fool ODK Validate, but it should work for all Pyxform-produced forms. Luckily the javarosa parser doesn't check the content of the choice_filter.

**Comment by MartijnR** [comment]
Bump @dorey, @ukanga, @tinok, @mberg. Who is going to add this to pyxform? 

Currently this Enketo feature is only supported by ODK Aggregate.

**Comment by mberg** [comment]
What's needed? Is there a ticket for this?

**Comment by dorey** [comment]
[I wrote it out into a test here using the 'pyxform_test_case' syntax](https://gist.github.com/dorey/58b5a2db8879a6579113) ( from pr #28 ).

@MartijnR, If that test describes all that's required, we can take a stab at it in the next couple weeks.

**Comment by MartijnR** [comment]
beautiful @dorey :+1: The only thing to change in the tests, is the ODK Validate trick, either by removing the self-closing `/` in the model_contains tests or by adding the `<root><item><name/><label/></item></root>` template. Former might be more attractive perhaps.

**Comment by mberg** [comment]
Martijn,

Would this enable pull csv like functionality in enketo express?

Matt

**Comment by MartijnR** [comment]
Yes, but differently, using a sane XForm syntax. The pulldata function is not supported, but I don't think we need it with the above method. We can use the regular choice_filter to do the same, so there is no difference between external and internal data in how to query this data.

**Comment by MartijnR** [comment]
The dummy content trick to fool ODK Validate is actually problematic. This works:

|name|label|country|
|-------|------|
|ams    | Amsterdam| nl|
|den   | Denver | usa|
| nyc | New York City | usa|

```xml
<instance id="cities" src="jr://file/cities.xml" >
    <!-- the following line is necessary for some xform parsers -->
    <root><item><name/><label/></item></root>
</instance>
```

But only if the itemset is using <value="

**Comment by MartijnR** [comment]
sorry, I removed my earlier weird comment...

I wonder if, after the recent changes wrt to column 'value' we should output instead:

```xml
<value ref="value"/> <!-- ref="value" instead of "name" -->
<label ref="label"/>
```

This would change the ODK-validate trick into:

```xml
<instance id="cities" src="jr://file/cities.xml" >
    <!-- the following line is necessary for some xform parsers -->
    <root><item><value/><label/></item></root>
</instance>
```

and thus require a value and label column (csv) or node (XML) in the external document.

**Comment by MartijnR** [comment]
Actually "value" instead of "name" doesn't seem to work in XLSForm (for regular choices sheet). So let's stick with using "name". 

I'm updating all the snippets above.

Sample XForm + XML media: [Archive.zip](https://github.com/XLSForm/pyxform/files/400352/Archive.zip)  [live](https://enke.to/::YYyg)
Sample XForm + CSV media:

**Comment by ukanga** [comment]
@MartijnR I notice that the form.xml in [external_xml.zip](https://github.com/XLSForm/pyxform/files/400352/Archive.zip) makes use of `<instance id="cities" src="jr://file/cities.xml">` and what pyxform currently generates is `<instance id="cities" src="jr://file-xml/cities.xml">`. Is this going to be an issue?

Also, what content type does enketo expect? The XML example https://enketo-stage.ona.io/::YYmJ seems Enketo is attempting a CSV processing instead of XML.

**Comment by MartijnR** [comment]
@ukanga, when looking at the code only, it seems like Enketo may (accidentally) be lenient towards this. However, `jr:file-xml` is definitely not correct. Sorry I missed this. For XML files it should be `jr://file/cities.xml`. (PS. this has now become [part of the official ODK XForms spec](https://opendatakit.github.io/xforms-spec/#secondary-instances---external))

Content-type should be appropriate for the source. At the moment, in Enketo if the (jquery get) result is not an XML Document it will be considered CSV. I think generally it should be `text/xml` or `application/xml` for XML and `text/csv` for CSV.

**Comment by MartijnR** [comment]
I've added an issue to EE as the explicitness of the jr:file or jr:file-csv connectors should probably be used to parse correctly regardless of the Content-Type. https://github.com/kobotoolbox/enketo-express/issues/710

**Comment by ukanga** [comment]
Thanks @MartijnR. I hope this is appropriate then https://github.com/XLSForm/pyxform/issues/106.
