### ISSUE TITLE
Calculations should only occur on the calculate question types

### ISSUE THREAD

**Issue by WinnyTroy** [XLSForm/pyxform#325]
| type | name   | label  | calculation |
|------|--------|--------|-------------|
| text | random | Random | 4*6         |

At the moment, this is converted successfully to generate xml that contains this:
`<bind calculate="4*6" nodeset="/demo_file/random" type="string"/>`

This should not be the case, as calculations should only be valid in calculate question types.

**Comment by lognaturel** [comment]
This is a very valuable feature! It does have to be either combined with `read_only` or `once(calc)`/`if(. = '', calc, '')`/`coalesce(., calc)` so that the calculation doesn't overwrite user data. Perhaps there could be a warning added but we'd lose some really important functionality if this were blocked.

See https://docs.opendatakit.org/form-logic/#setting-default-responses

**Comment by lognaturel** [comment]
On additional thought, maybe once [true dynamic defaults](https://forum.opendatakit.org/t/xlsform-spec-proposal-add-syntax-to-make-it-easy-to-use-a-value-from-the-last-saved-instance/18814/22) are in this is a good idea. It would break some existing forms that people would want to edit but the warning could tell them how to use the `default` column to achieve what they want.

**Comment by tedrick** [comment]
I would second @lognaturel's statement on the value of calculations in non-`calculate` questions.  We have seen many, many customers use calculations in other field types; this provides visual feedback to the user of the calculation to confirm expectations (as examples, determining a re-inspection date for a feature, or overall hazard level based on inputs).  As pointed out, this also provides a way to supply an appropriate default value that can then be overwritten by the user if the calculated answer is not correct given field conditions.

**Comment by lognaturel** [comment]
We now explicitly consider `calculation` for any type a way to get typed calculates - #70.
