### ISSUE TITLE
Generated itemsets.csv file is blank

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#326]
#### Software and hardware versions 
pyxform 0.14.0

#### Problem description
Generated `itemsets.csv` file is always blank.

#### Steps to reproduce the problem
Convert a form with a `select_one_external` field such as [select_one_external.xlsx](https://github.com/XLSForm/pyxform/files/3383992/select_one_external.xlsx). Cat the `itemsets.csv` file.

#### Expected behavior
`itemsets.csv` file should be populated by items in `external_choices` sheet.

#### Other information 
User report: https://forum.opendatakit.org/t/external-selects-stopped-working/20863

**Comment by lognaturel** [comment]
`git bisect` reveals that 3c72349 is the commit that broke this.

**Comment by ukanga** [comment]
Closed by #323
