### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by ukanga** [XLSForm/pyxform#327]
There is a need to make sure the code:

1. has tests addressing the issue
2. is tested using `PyxformTestCase` and markdown based XLSForms, see examples in [pyxform/tests_v1](https://github.com/XLSForm/pyxform/tree/dd584b85032fcd74ba55f0ab3ecaf22e26e7d7a8/pyxform/tests_v1) ;not adding any new binary files into the codebase
3. is formatted with [black](https://github.com/python/black)
4. is not reducing test coverage
5. ..

Having all or some of this documented in contributing.md might be easier to point to when reviewing PRs.

**Comment by lindsay-stevens** [comment]
Since this issue was opened, the readme covers these topics, the GitHub PR template has a quality checklist, and PRs are automatically linted and tested.
