### ISSUE TITLE
Support PDF File Upload question type

### ISSUE THREAD

**Issue by pld** [XLSForm/pyxform#33]

**Comment by dorey** [comment]
What would the question type's ID be and how would it be represented in XML?

**Comment by pld** [comment]
I might have misinterpreted something, getting some clarification, will respond (or just close) after

**Comment by MartijnR** [comment]
details of this feature are here: https://github.com/SEL-Columbia/pyxform/issues/109

(this feature in Enketo was funded through Ona)

**Comment by MartijnR** [comment]
@ukanga To solve the recent issue with Chrome, it's probably best to specify exactly which formats to enable. I propose using this value for `mediatype` instead:

```
mediatype="text/plain,application/pdf,application/vnd.ms-excel,application/msword,text/richtext,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/zip,application/x-zip,application/x-zip-compressed"
```

It includes: .text, .pdf, .xls, .rtf, .xdoc, .xlsx, .zip.

I imagine we'll likely be adding more formats in the future.

**Comment by ukanga** [comment]
This is more specific, I much prefer this approach. I will make the changes and push soon.

**Comment by ukanga** [comment]
@MartijnR should it be possible for someone to specify a specific format e.g if only interested in pdfs?

**Comment by MartijnR** [comment]
Yes, that makes sense. Easy to add if there is a user demand for it (type=pdf, type=document, type=spreadsheet).  On the enketo side it doesn't require changes, I think. Enketo will just copy the mediatype value that is specified in the XForm.

**Comment by ukanga** [comment]
I would propose an appearance column option, just in case it's missing we include the full list.

**Comment by MartijnR** [comment]
Hmm. I'd much rather add additional types. We should really stick to using appearances only for display styles.

Is type=file available now?

**Comment by ukanga** [comment]
It will be available if #37 is merged, but I can make changes on it to only support `pdf | spreadsheet | document | compressed?`.

**Comment by ukanga** [comment]
Would we need to support `file` still?

**Comment by MartijnR** [comment]
I think we need `file` to catch "all" formats (the client's contract including a _generic file input_). The others could be added in the future perhaps, when the need arises. 

I just noticed a small issue. Unlike with the initial `application/*` mediatype, ODK Collect will now just show a text input field. I don't think there is a way around this.

**Comment by MartijnR** [comment]
Deleted my comment. I was wrong. It was only Aggregate that supported this.
