### ISSUE TITLE
Set XML root explicitly in XLSForm settings

### ISSUE THREAD

**Issue by jkpr** [XLSForm/pyxform#335]
The form name (form title) is used as the XML root for the instance.
https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2json.py#L395

The form title is meant to be descriptive, but it does not need that purpose in the XML. It would save a lot of file space to change the root from the form title to something short.

For example, I have a simple form 580 lines long in the XML. The form title `GHR6-Listing-v8-jef` appears 297 times. Nearly all of them are just as part of XPaths to nodesets. If it could be shortened to just `LS` and save nearly 5KB.

In my fork of `pyxform`, I have a setting in the settings tab that is called `xml_root` and if it is found, that value is used as the XML root.

**Comment by lognaturel** [comment]
Thanks! See #130 and #152.

**Comment by jkpr** [comment]
Great! #152 is fresh, so this is on your minds.

**Comment by jkpr** [comment]
@lognaturel I was working on applying this change to make a fork of `pyxform` and it looks like this is already implemented in the code. I don't know why I missed it before. In the settings, I can simply use `name` as a key and then set the value to what I would like, such as `LS` in my example above.

In the conversations at #130 and #152, I do not see conversation about this setting, so maybe everyone knows about it. It isn't published on xlsform.org, though.

**Comment by jkpr** [comment]
I'm closing this as it is being addressed by #368
