### ISSUE TITLE
big-image and media::big-image column heading for itext tag is not available in XLSForm

### ISSUE THREAD

**Issue by mitchellsundt** [XLSForm/pyxform#34]
There is a "big-image" itext value tag type that is not supported by XLSForm.

Usage section below is copied from this page: https://opendatakit.org/help/form-design/guidelines/

---

Itext value tag types

The possible choices for the form attribute of the itext <value> tag are:

```
"long",
"short",
"image",
"audio",
"video", and
"big-image".
```

By default, itext "image" values are not clickable. However, if you also include a "big-image", the image displayed by "image" will be clickable and will display a pannable, zoomable view of the file specified by "big-image". You can return to your form after opening a "big-image" by hitting the phone's "back" button. Specifying "big-image" alone has no effect, you must always include "image".

**Comment by MartijnR** [comment]
+1
