### ISSUE TITLE
start-geopoint fails ODK Validate validation because of stub setgeopoint implementation

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#351]
#341 adds support for `start-geopoint`. The XForms output that is generated is what is described in the spec and works in e.g. Collect. However, it fails Validate because JavaRosa's stub implementation of the `setgeopoint` action provides a string that then is attempted to cast to a geopoint.

I'm not sure whether to address this at the JavaRosa or Validate level. Either way, I think we'd need to supply a bogus value in geopoint format rather than an arbitrary string. Filing this here so we know there's still work to do on that front.

CC @yanokwa

**Comment by lognaturel** [comment]
A little retrospection:
- @yanokwa submitted https://github.com/XLSForm/pyxform/pull/341 adding `start-geopoint` support
- He noted that it wouldn't pass validation until https://github.com/XLSForm/pyxform/pull/341#issuecomment-514678081 was merged
- https://github.com/XLSForm/pyxform/pull/341 was merged
- I discovered this when I tried to build a sample form to demonstrate `start-geopoint` added in https://github.com/XLSForm/pyxform/pull/341.

I think we need to make sure to actually try a sample form and/or make sure to run the tests with Validate on.

The reason for the issue:
- JavaRosa can't provide location information directly so it includes a stub for the `setgeopoint` action that writes the text "no implementation" when triggered.
- My sample form includes a `start-geopoint` meant to set the value of a node of type `geopoint`.
- Validate runs through the form as though it were being filled. I keep forgetting this. In this case, it means the action is triggered.
- When JR tries to set "no implementation" as the value of the node of type `geopoint`, there's a casting crash.

I've gone back and forth on where to fix this. I'm going to do a Validate change for now and we can always adjust if needed.

**Comment by yanokwa** [comment]
I'm trying to think of a more systemic way for us to catch this class of problem. @ukanga would it be crazy to change all (most?) pyxforms tests to run through Validate.

**Comment by lognaturel** [comment]
> would it be crazy to change all (most?) pyxforms tests to run through Validate.

I think it would take too long to run and not be valuable in most cases. As reviewers, I think we need to remember check when a Validate check should be required.

How about adding it to the PR template so that both the submitter and the reviewer get a reminder?
