### ISSUE TITLE
Default language for labels and constraint messages when explicit default language is not specified

### ISSUE THREAD

**Issue by ajaydivakaran** [XLSForm/pyxform#36]
Given a xlsform where the labels and constraint messages are present in multiple languages and there is no explicit default language specified.
My question is:
In the generated xform what would be the default/first language?

**Comment by lognaturel** [comment]
The first one listed is the implicit default. 

@ajaydivakaran Sorry you didn't get a response earlier! Generally, support channels like https://forum.opendatakit.org/c/support are better for this kind of question.
