### ISSUE TITLE
Duplicate choice name message is confusing

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#373]
#310 introduced a `allow_choice_duplicates` setting. The error message when that setting is not set and a list has duplicate choice names is: "There does not seem to be a `allow_choice_duplicates` column header defined in your settings sheet. You must have set `allow_choice_duplicates` setting in your settings sheet to have duplicate choice list names in your choices sheet"

The message should lead with what is wrong with the form (a choice list has duplicate choice names).

I propose something like:
"One or more of your choice lists contains duplicate choice names. That means the choices with the same name will be impossible to differentiate in analysis. If this is intentional, you can set the `allow_choice_duplicates` setting. Read more at `<url once documented>`."

Having a URL means there can be an example which would be helpful to users who may not understand the problem with duplicate choice names.

It might also be helpful to identify the lists and/or the choices that are affected. https://github.com/XLSForm/pyxform/pull/310/files#diff-b29aeb282b118614b8333cdfc19f700dR494 attempts to do this but it should be revisited because it only happens if the `allow_choice_duplicates` is defined in the settings sheet but not set to yes|Yes.

**Comment by qlands** [comment]
I'm just wondering why to allow it in the first place.
Giving three choices:
1=A
1=B
1=C
Then A = B = C
Therefore from I would just one choice:
1= "A, B, C"

**Comment by lognaturel** [comment]
Good question, @qlands! Some surveys may involve giving weights or points to different categories of items. As a silly example, you can imagine the question "what did you eat today" with the following choices:
2=Broccoli 
2=Carrots
2=Banana
1=Orange
1=Celery
0=Potato chips
-1=Candy

If the goal is to get some "healthy diet score", you may not care about the actual foods eaten but only about the total score. There are various examples of users doing this on the forum.

**Comment by lognaturel** [comment]
Another legitimate case where there could be duplicate choice names is when those are differentiated by another column's value which corresponds to a prior question in a select cascade.

For example, two towns may have the same name but they may be differentiated by the state that they're in (e.g. Paris, Arkansas vs. Paris, Texas).

Documentation PR up at https://github.com/XLSForm/xlsform.github.io/pull/184 and code PR up at https://github.com/XLSForm/pyxform/pull/418.
