### ISSUE TITLE
Itemset from previous answers - select one from ${node}

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#38]
Triggered by [this question](https://groups.google.com/forum/#!topic/formhub-users/K6hcV3Bh77Y)

It exposes the so-far-untapped XForm capability to create a choice list from previous answers (in a repeat).

It could have a wider implication by avoiding the more difficult indexed-repeat() or a combination of concat() and selected-at(). 

After discussion with @dorey we came up with the following initial syntax suggestion:

| type | name | label | choice_filter |
| --- | --- | --- | --- |
| begin repeat | rep |  |  |
| text | name | Enter name |  |
| end repeat |  |  |  |
| **select one from ${name}** | choice | Choose | string-length(./name) > 0 |

``` xml
<select1 ref="/data/choice">
   <label>Choose name</label>
   <itemset nodeset="/data/rep[string-length(./name) > 0]">
       <label ref="name"/>
       <value ref="name"/>
   </itemset>
</select1>
```

The `ref` attribute is the nodename of ${name} and the `nodeset` attribute is the parent of  ${name} with an optional choice filter.

**Comment by MartijnR** [comment]
_select multiple_ support might be difficult because we cannot allow spaces in the answers...

**Comment by dorey** [comment]
I like the idea of adding the ability to reference previous repeats. After thinking about the syntax a little more, I'm wondering if we could come up with a better way to specify it in the xlsform. Main reasons--

* <code>select one from ${name}</code> could require new regex changes for parsing the type field. Even if we went with <code>select_one ${name}</code> there's a high probability that parsers in pyxform and various xlsform form-builders and parsers (<img src="http://vignette2.wikia.nocookie.net/banjokazooie/images/5/51/Whistling.gif/revision/latest?cb=20090408112203" />) would need their regex fixed. And though we could do it on individual cases, it'd be cleaner if we could settle on a way of extending functionality that doesn't involve changing the regex.
* I vaguely remember people wanting to move away from <code>{ "type": "select_one listname" }</code> towards something like <code>{ "type": "select_one", "list_name": "listname" }</code>. Which would make parsing and validation of the form easier and more precise. (Note: I may have imagined this conversation)

How about:
<table>
<tr>
<th>type
</th>
</tr>
<tr>
<td>select_one ${prev_name}
</td>
</tr>
</table>
* still might need regex changes

or

<table>
<tr>
<th>type
</th>
<th>list name
</th>
</tr>
<tr>
<td>select_one
</td>
<td>${prev_name}
</td>
</tr>
</table>

**Comment by MartijnR** [comment]
I can see that would make sense from a developer perspective. Maybe move that discussion to a different issue, since it relates to all select type questions?

**Comment by ukanga** [comment]
I took the approach of using `select one ${prev_name}` in #381, it seemed the easiest way to implement without adding any additional syntax other than a reference to a previous field.

Any thoughts on the implementation?

**Comment by MartijnR** [comment]
Just happy thoughts about the feature from me and that test looks looks good.

**Comment by lognaturel** [comment]
@MartijnR you may want to check out @DavisRayM's progress at #472 and some of my comments to see whether you agree. I now see that in your initial example you weren't using `${}` syntax in the `choice_filter`. Was that intentional? I initially thought it would be easier to let users use `${}` but maybe it's reasonable to explain that fields within the target repeat are written as `./<field name>`.

**Comment by MartijnR** [comment]
Thanks! I will do that. I believe that not using `${}` syntax in the choice_filter was not intentional or maybe it was because we weren't producing relative paths at that time. Seems better to use the `${}`syntax in examples (and support it).
