### ISSUE TITLE
Choice lists for all selects are generated as instances if any list uses a choice filter

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#387]
From @nribeka at https://github.com/XLSForm/pyxform/issues/176#issuecomment-537986739:

If the parser encounter ```choice_filter``` it will add an instance for each choice list.

So if you have form like this:

type | name | label | choice_filter
-- | -- | -- | --
select_one states | state | The State | state = 'VA'

list_name | name | label
-- | -- | --
states | VA | Virginia
states | IN | Indiana
fruits | apple | Apple
fruits | banana | Banana

You will ended up with form like the following:

```
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>data</h:title>
    <model>
      <instance>
        <data id="data">
          <state/>
          <meta>
            <instanceID/>
          </meta>
        </data>
      </instance>
      <instance id="states">
        <root>
          <item>
            <label>Virginia</label>
            <name>VA</name>
          </item>
          <item>
            <label>Indiana</label>
            <name>IN</name>
          </item>
        </root>
      </instance>
      <instance id="fruits">
        <root>
          <item>
            <label>Apple</label>
            <name>apple</name>
          </item>
          <item>
            <label>Banana</label>
            <name>banana</name>
          </item>
        </root>
      </instance>
      <bind nodeset="/data/state" type="select1"/>
      <bind jr:preload="uid" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <select1 ref="/data/state">
      <label>The State</label>
      <itemset nodeset="instance('states')/root/item[state = 'VA']">
        <value ref="name"/>
        <label ref="label"/>
      </itemset>
    </select1>
  </h:body>
</h:html>
```

I believe this is the cause of problems reported at https://forum.opendatakit.org/t/prevent-duplicates-based-on-key-data-in-csv-with-choice-filter/20062

**Comment by lognaturel** [comment]
Here's another user running into this bug: https://forum.getodk.org/t/error-the-same-instance-id-will-be-generated-for-different-external-instance-source-uris/26328

**Comment by percezione** [comment]
Hi, I am having the same problem. I'm trying to use select_one_from_file file.csv and choice_filter on another question in the form and I'm getting the error

**Comment by lognaturel** [comment]
Replaced by #603.
