### ISSUE TITLE
Form title and form_id should not default to data

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#388]
https://github.com/XLSForm/pyxform/pull/375 uses a default root node name of `data` which is great. It also sets the form title and the form ID to `data` which it should not.

Setting the form ID to `data` is really problematic because the form ID is what both clients and servers use to uniquely identify forms. I think the best option is to default to the filename. I don't see any restriction placed on the `id` structure either at https://opendatakit.github.io/xforms-spec/#primary-instance or at https://docs.opendatakit.org/openrosa-form-list/#query-parameters so it should be ok to include spaces, unicode, and any other characters that a filename could contain. Note that prior to https://github.com/XLSForm/pyxform/pull/375, the filename had to be XML-safe but that this is no longer the case. I have confirmed that Collect and Central have no problem with a form id that contains spaces and unicode.

I think users would expect the form title to match the filename unless they explicitly override it. I can't think of any problems with doing this.

I believe this will mean passing the filename separately from the root node name.

CC @nribeka @ukanga @MartijnR

**Comment by nribeka** [comment]
The workaround is setting the ```form_id``` in the settings sheet, right?

**Comment by lognaturel** [comment]
Setting the `form_id` in the settings sheet sets the id correctly, yes. The issue is with the fallback behavior which should not have been changed.

**Comment by nribeka** [comment]
I think we need to pass in the filename as separate parameter and then changing the ```id_string``` assignment from this:
```
    id_string = settings.get(constants.ID_STRING, form_name)
````
to something like this:
```
    id_string = settings.get(constants.ID_STRING, filename)
```

Is this the approach that you're thinking @lognaturel?

**Comment by lognaturel** [comment]
Yes, that sounds right to me, @nribeka.

**Comment by nribeka** [comment]
Draft PR added to attempt to fix this.
