### ISSUE TITLE
Bad XLSForm calculation breaks code, and why are errors not dealt with when using xls2xform.py as main?

### ISSUE THREAD

**Issue by jkpr** [XLSForm/pyxform#39]
Wonderful work so far on pyxform! I use pyxform to automate xform creation for my project. I have noticed that a bad calculate in XLSForm (a survey with a single line, e.g. `{type: 'calculate', name: 'badcalc', label: 'This calculation fails', calculation:'because it doesn't know what to do'}`) produces an error such as 

```
Traceback (most recent call last):
  File "/path/to/package/pyxform/pyxform/xls2xform.py", line 65, in <module>
    warnings = xls2xform_convert(args.path_to_XLSForm, args.output_path)
  File "/path/to/package/pyxform/pyxform/xls2xform.py", line 22, in xls2xform_convert
     survey.print_xform_to_file(xform_path, validate=True, warnings=warnings)
  File "/path/to/package/pyxform/pyxform/survey.py", line 446, in print_xform_to_file
    warnings.extend(check_xform(path))
  File "/path/to/package/pyxform/pyxform/odk_validate/__init__.py", line 112, in check_xform
     m = 'ODK Validate Errors:\n' + _cleanup_errors(stderr)
  File "/path/to/package/pyxform/pyxform/odk_validate/__init__.py", line 86, in _cleanup_errors
return u'\n'.join(k)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 170: ordinal not in range(128)
```

This is not very informative. The problem is that the current code keeps python's place indicator of where the error is. This cannot be converted to unicode implicitly, so an error is thrown. I have made a fix to the code (locally), and now the error message says 

```
ODK Validate Errors:
org.javarosa.xform.parse.XFormParseException: Invalid calculate for the bind attached to "${badcalc}" : Couldn't understand the expression starting at this point: because͎it doesn't know... in expression because it doesn't know what to do

>> XForm is invalid. See above for the errors.

Result: Invalid
```

But now the problem is that an ODK Validate error raises an unhandled `Exception`. A change to the main method (read: inside the `if __name__ == '__main__':` suite) in `xls2xform.py` to handle these exceptions would be pretty easy.

Nafundi's XLSForm Offline handles conversion errors, but does not handle the bad calculate. I would have thought that Nafundi's changes would make it back into the code, but I suppose not.

I would be happy to contribute what I have done to the project. What is the process to contribute/submit pull requests? What about creating test cases or checking that my new code does not break the old code?

**Comment by ukanga** [comment]
A pull request would be welcome. I suppose the process is you fork, make your changes and then submit a pull request. If tests are included that would be awesome.

**Comment by jkpr** [comment]
I submitted a pull request a while ago. Have you had time to look at it? Any comments?

**Comment by lognaturel** [comment]
Another example of this kind of problem: https://forum.opendatakit.org/t/conversion-error-ascii-codec-cant-decode/9733

It looks like the PR was XLSForm/pyxform#41 and that there were issues with the tests. Will try to look at this again some time unless anyone else beats me to it. Better messages here would save a lot of troubleshooting time.

**Comment by KeynesYouDigIt** [comment]
Im happy to take a crack at this, someone stop me if youre taking it

**Comment by p-netm** [comment]
from the same survey line that caused an error in the issue description(with a slight modification in the calculation column). I get the following traceback
```bash
Traceback (most recent call last):
  File "/home/peter/.virtualenvs/pyform/bin/xls2xform", line 11, in <module>
    load_entry_point('pyxform', 'console_scripts', 'xls2xform')()
  File "/home/peter/Desktop/xls/pyxform/pyxform/xls2xform.py", line 152, in main_cli
    enketo=args.enketo_validate)
  File "/home/peter/Desktop/xls/pyxform/pyxform/xls2xform.py", line 38, in xls2xform_convert
    warnings=warnings, enketo=enketo)
  File "/home/peter/Desktop/xls/pyxform/pyxform/survey.py", line 820, in print_xform_to_file
    warnings.extend(odk_validate.check_xform(path))
  File "/home/peter/Desktop/xls/pyxform/pyxform/validators/odk_validate/__init__.py", line 76, in check_xform
    b'ODK Validate Errors:\n' + ErrorCleaner.odk_validate(stderr).encode('utf-8'))
pyxform.validators.odk_validate.ODKValidateError: b'ODK Validate Errors:\n>> XForm is invalid. See 
above for the errors.\norg.javarosa.xform.parse.XFormParseException: Invalid calculate for the bind 
attached to "${badcalc}" : Couldn\'t understand the expression starting at this point: something\xcd
\x8eweird in expression something weird\n\nResult: Invalid'
```
for another instance of a similar error, as noted by @lognaturel in the link https://forum.opendatakit.org/t/conversion-error-ascii-codec-cant-decode/9733; The traceback produced is:

```bash
Traceback (most recent call last):
  File "/home/peter/.virtualenvs/pyform/bin/xls2xform", line 11, in <module>
    load_entry_point('pyxform', 'console_scripts', 'xls2xform')()
  File "/home/peter/Desktop/xls/pyxform/pyxform/xls2xform.py", line 152, in main_cli
    enketo=args.enketo_validate)
  File "/home/peter/Desktop/xls/pyxform/pyxform/xls2xform.py", line 38, in xls2xform_convert
    warnings=warnings, enketo=enketo)
  File "/home/peter/Desktop/xls/pyxform/pyxform/survey.py", line 820, in print_xform_to_file
    warnings.extend(odk_validate.check_xform(path))
  File "/home/peter/Desktop/xls/pyxform/pyxform/validators/odk_validate/__init__.py", line 76, in check_xform
    b'ODK Validate Errors:\n' + ErrorCleaner.odk_validate(stderr).encode('utf-8'))
pyxform.validators.odk_validate.ODKValidateError: b"ODK Validate Errors:\n>> XForm is invalid. See 
above for the errors.\norg.javarosa.xform.parse.XFormParseException: Encountered a problem with 
display condition for node [${person_name}] at line: selected(${gender, 'male'), Couldn't understand 
the expression starting at this point: selected(\xcd\x8e${gender, 'male...\n\nResult: Invalid"
```
Correct me if am wrong but the issue was that the error messages were deemed uninformative, which seems to not be the case anymore. I think some one must have fixed this. @ukanga if this is the case can this be closed.
