### ISSUE TITLE
Create xform2xls

### ISSUE THREAD

**Issue by jkpr** [XLSForm/pyxform#390]
Xform and XLSForm are equal mappings to each other, when considering only the essential details.

I think it might be a good / interesting idea to make function that takes a valid Xform and creates an XLSForm. This could be helpful in a few scenarios, such as

1. You have an Xform (from ODK Aggregate, directly from the phone), and you want to see it in XLSForm format. Other tools can compare Excel files. A user can more easily understand XLS.
2. Version control is easier with XML than XLSX, so keeping XML only is feasible since there is a way to get XLSForm.

I know this would be useful in my work. It seems like we might be close with `xform2json`? Just need to go one more step to Excel.

**Comment by lindsay-stevens** [comment]
Please open a thread on the forum to discuss feature requests https://forum.getodk.org/
