### ISSUE TITLE
Can't covert forms with count-non-empty function

### ISSUE THREAD

**Issue by grzesiek2010** [XLSForm/pyxform#391]
I tried to convert a form which contains [count-non-empty](https://docs.opendatakit.org/form-operators-functions/?highlight=count%20selected#count-non-empty) function but to no avail.
The returned error is:
`pyxform.validators.odk_validate.ODKValidateError: b"ODK Validate Errors:\n>> Something broke the parser. See above for a hint.\nError evaluating field 'weight_mean2': unrecognized data type in 'calculate' expression: java.lang.Integer\nCaused by: java.lang.RuntimeException: unrecognized data type in 'calculate' expression: java.lang.Integer\n\t... 11 more\n\nThe following files failed validation:\ntest.xml\n\nResult: Invalid"
`

Sample form: 
[test.xlsx](https://github.com/XLSForm/pyxform/files/3803498/test.xlsx)

**Comment by lognaturel** [comment]
This is caused by https://github.com/opendatakit/javarosa/issues/509.
