### ISSUE TITLE
Double quotes in pulldata parameter expression results in wrong instance ID and CSV filename being generated

### ISSUE THREAD

**Issue by danbjoseph** [XLSForm/pyxform#398]
I designed a form to pull data from a CSV as described in the [XLSForm docs](https://xlsform.org/en/#how-to-pull-data-from-csv); see https://github.com/opendatakit/central/issues/115 for details of what I tried. And the conversion results in a reference to a "RC.csv" file despite the XLSForm xlsx referencing a filename of "registered": `pulldata('registered','first','rcid',concat("RC",${rcid}))` 

What I did differently from the example which may be causing the issue was the use of the `concat()` within the `pulldata()` when providing the lookup value, and the use of double quotes to provide a string as part of that?

**Comment by lognaturel** [comment]
Thanks for your patience with this, @danbjoseph. Your hunch is correct -- as you may have discovered by now, using single quotes for the `concat('RC',${rcid})` expression makes everything work as expected.

Is that a change that you can make in your form design for now? I think we should definitely address this but it doesn't feel urgent given that there's a workaround.

**Comment by lognaturel** [comment]
Adding calculations 
```
pulldata(‘registered’,’first’,’rcid’,concat("Foo",${rcid}))
pulldata(‘registered’,’last','rcid',concat('RC',${rcid}))
pulldata(‘registered’,’envelope','rcid',concat("Bar",${rcid}))

```

**Comment by danbjoseph** [comment]
The form was just a test while exploring Central. Is the work around something worth adding to the docs? Or are you working on the `csv` module fix in the near-future?

**Comment by lognaturel** [comment]
It's a good catch so thank you! I ended up getting curious so I have a fix. I want to give it another think-through because now I don't actually think the `csv` module is all that helpful and that splitting on a comma is sufficient. It should be in the next pyxform release which hopefully will be soon.
