### ISSUE TITLE
Empty label with list-nolabel contains a space, crashes older ODK Collects

### ISSUE THREAD

**Issue by jkpr** [XLSForm/pyxform#399]
The form is meant to create a table. The labels at the top of the table have no entry in my XLSForm "label" column. I have converted the attached ODK form using https://opendatakit.org/xlsform/

<img width="269" alt="Screenshot 2019-11-19 17 03 28" src="https://user-images.githubusercontent.com/3988950/69199961-8b131800-0aee-11ea-989e-4b91e52ddc1b.png">

In the converted XML body, the label tag contains a space, `<label> </label>` for `/no-label-test/G/labels`. This came to my attention since it crashes my older version of ODK Collect (1.4.8). Since my XLSForm is blank, it should be `<label></label>` (no space). When it is edited this way it does not crash my older ODK Collect.

The converted XML should not have a superfluous space here.

[no-label-test.xlsx](https://github.com/XLSForm/pyxform/files/3866773/no-label-test.xlsx)

**Comment by lindsay-stevens** [comment]
I think by now ODK Collect 1.4.8 is not supported. A question with no label or hint is not accepted by pyxform, but after adding an `appearance` of `label` it is accepted and the XForm result has the spacey label. It seems that the space is there to prevent a table-lists bug [as commented here](https://github.com/XLSForm/pyxform/blob/9d20bfec5128f53ec0d555f7187f3bc4881f667e/pyxform/survey_element.py#L109-L114), and [committed here](https://github.com/XLSForm/pyxform/commit/0b7cafbf4f9810f36f2f132dae34ce1039d520b2).

If this crash is still a problem and is reproducible, could you please re-open this issue? Thanks!
