### ISSUE TITLE
Add external instance when pulldata function is used

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#43]
This will create a reference to the external data in the XForm which means that strict XForm clients (such as Enketo) will be able to use this data. This means those clients could e.g. start supporting the pulldata() function without data being available _magically_.

Search for pulldata expressions in the calculation column, e.g. `pulldata('hhplotdata', 'plot1size', 'hhid_key', ${hhid})`.

If found:
0. extract id (first parameter of pulldata expression), in the example: "hhplotdata"
1. check if `<instance id="hhplotdata">` node exists
2. if not, add secondary instance to XForm output: 
```
<instance id="hhplotdata" src="jr://file-csv/hhplotdata.csv" />
```

**Comment by mberg** [comment]
Martijn - would this work for ODK or is that different?

**Comment by MartijnR** [comment]
Hi Matt, 

Yes, the extra instance should not break its existing functionality in ODK Collect. I expect ODK Collect is just ignoring this. (I tested with https://opendatakit.org/downloads/download-info/sample-preloading-form/).

Aggregate will also not have a problem with the additional instance.

I just want to emphasize that we're just talking about the pulldata() function (which retrieves a single value from an external data file).

**Comment by mberg** [comment]
OK - so we would just need to code forms with both options to support ODK
and enketo.  Ok cool

**Comment by MartijnR** [comment]
yes, adding the instance allows Enketo to implement pulldata in XPath because it is a part of the form (so in addition, Enketo would be able to use any other XPath expression on that data using instance('hhplotdata')/path/to/node syntax to refer to nodes - but this won't work in ODK collect).

**Comment by ukanga** [comment]
@MartijnR just to confirm, `search()` would not be part of this, right?

**Comment by MartijnR** [comment]
That's right, no search() support.

**Comment by ukanga** [comment]
@MartijnR you can test this on stage.ona.io

**Comment by MartijnR** [comment]
Great. Will do. When looking at the code, I'm just not sure about the .csv extension. I think the opendatakit.org example is for a file without any extension. But I guess, what matters is how it is included in the xformsManifest, so you may be able to tweak it there if necessary.

**Comment by MartijnR** [comment]
Ah never mind about extension. I was fooled by OS X ;).

**Comment by MartijnR** [comment]
All seems good to me.
