### ISSUE TITLE
Output empty `<label/>` instead of omitting it.

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#439]
Currently pyxform requires either a value in the "label" column or in the "hint" column for form controls (ie. questions in the body). This validation rule can remain unchanged.

However, as @tiritea discovered,  a `<label>` element is actually required according to the XForms spec. Therefore, we should include an empty `<label/>` (or `<label></label>`) element in the body output. This is currently not the case.

### Test 1

| type | name | label | hint |
|-----|--------|-----|----|
| text | a        |         | a hint |
| text | b       |A label |        |

```xml
<input ref="/data/a">
    <label/>
    <hint>a hint</hint>
</input>
<input ref="/data/b">
    <label>A label</label>
</input>
```

**Comment by lindsay-stevens** [comment]
@lognaturel / @MartijnR  it looks like the error for no hint comes from ODK Validate rather than pyxform. Should pyxform warn / error about no hint, or just emit a label to comply with the spec and ODK Validate?

It doesn't seem like an error is necessary, since adding the empty label XML node shouldn't affect how the survey works. But maybe it does for some tools?

**Comment by MartijnR** [comment]
Hi @lindsay-stevens. Welcome back!

> Should pyxform warn / error about no hint, or just emit a label to comply with the spec and ODK Validate?

If ODK Validate does not get fooled by an empty label (and still requires either a label or hint text content), then I think outputting an empty label in pyxform is all that is required.

**Comment by KeynesYouDigIt** [comment]
@lindsay-stevens Are you already working on this? If not I might be able to take a swing at it! let me know either way

**Comment by lindsay-stevens** [comment]
@MartijnR thanks!
@KeynesYouDigIt yes I have a draft that I'll create a PR for this week.
