### ISSUE TITLE
Catch basic spelling errors on worksheet names

### ISSUE THREAD

**Issue by issa-tseng** [XLSForm/pyxform#443]
For the `survey`, `choices`, and `settings` worksheets, it could be nice to catch basic spelling errors and warn the user.

So, eg, if there is no `settings` sheet, but there is some other sheet with a Levenshtein distance < 2 from `settings` (say somebody like @seadowg accidentally labelled it `setting`), a warning could be issued.

Filed on suggestion from @lognaturel.

**Comment by seadowg** [comment]
I feel seen
