### ISSUE TITLE
Maximum recursion depth can be reached when a label has many references

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#444]
https://forum.getodk.org/t/error-maximum-recursion-depth-exceeded/26792

I think the first thing to do is to identify what recursive call this his hitting and whether it really does need to be recursive.

**Comment by delcroip** [comment]
I think it is this one
https://github.com/XLSForm/pyxform/blob/b7474d8655e54c5255e209177f4f1373e6918ee3/pyxform/survey.py#L848
