### ISSUE TITLE
<output> inside repeat has absolute path instead of relative

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#446]
type | name | label::English | calculation
-- | -- | -- | --
begin repeat | member |   |  
calculate | pos |   | position(..)
text | member_name | Name of ${pos} |  
end repeat |   |   |  

[xlsform](https://docs.google.com/spreadsheets/d/1QGpOlm2sTrd-C93Kyr9V2xW7fPghHd6BlaH8Duio4to/edit?usp=sharing)

The above form contains `<output value=" /data/member/pos "/>` instead of the expected `<output value=" ../pos "/>`.

This is only the case when the output is placed as a descendant of `<itext>`. The above form with a `label` column instead of `label::English` works fine.

**Comment by MartijnR** [comment]
Would be great to wait for this fix before the next release **if** we get a PR for this fix soon, say this week. Am discussing with major user about perhaps supporting this as a priority.

**Comment by gushil** [comment]
Hi @MartijnR I've created PR #450 to address this issue. Waiting for the review.

Thanks.

**Comment by lognaturel** [comment]
Thanks again, @gushil! Quick Github tip -- if you use a [closing word](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references) before tagging the corresponding issue in a PR description, merging that PR will automatically close the issue.
