### ISSUE TITLE
New non-text calculations output a missing-label warning

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#451]
I think these warnings are no longer helpful, in the forthcoming release that includes non-text calculations.

Example:

type | name | label | hint | calculation
-- | -- | -- | -- | --
dateTime | a |   |   | now()
integer | b |   |   | 1 div 1
note | note | Hello World |   |  

[XLSForm](https://docs.google.com/spreadsheets/d/1XiyuBXNOZ9SeKfTmw_ZD3xAVmdGQ3TJFiGTtY9JGMCI/edit?usp=sharing)

Outputs (in latest master):

```bash
Warnings:
[row : 2] Question has no label: {'type': 'dateTime', 'name': 'a', 'bind': {'calculate': 'now()'}}
[row : 3] Question has no label: {'type': 'integer', 'name': 'b', 'bind': {'calculate': '1 div 1'}}
```

The warning remains helpful:

* if the question has no value in the calculation column and has no dynamic default value, as in example below:

type | name | label | hint 
-- | -- | -- | -- 
dateTime | a |   |   
integer | b |   |

**Comment by pbowen-oc** [comment]
The current error messages are preventing forms form being uploaded as expected. Since old-style calculate items are also required to have a calculation, this is preventing forms from having non-visible items with default values that can be utilized by other items on the form in their default value expressions. Note that default values expressions that reference calculated values don't seem to work since the calculations are not performed prior to the default value expressions being evaluated.

**Comment by MartijnR** [comment]
> Since old-style calculate items are also required to have a calculation

I added a separate issue for this: https://github.com/XLSForm/pyxform/issues/454

> Note that default values expressions that reference calculated values don't seem to work since the calculations are not performed prior to the default value expressions being evaluated.

Added a documentation issue for this: https://github.com/XLSForm/xlsform.github.io/issues/204 Maybe one day we could show a warning in pyxform for this as that would be ideal.

**Comment by pbowen-oc** [comment]
@gushil - Can you work on this?

@MartijnR - Should the warning be based on not having a label or based on not having a label or hint? I thought it was permitted to have an item in the UI with no label if it had a hint?

**Comment by MartijnR** [comment]
Great, thanks!

> Should the warning be based on not having a label or based on not having a label or hint? I thought it was permitted to have an item in the UI with no label if it had a hint?

Yes, that's right, that is permitted. I think that part of the logic in pyxform can remain unchanged. We just need to exclude the warning(s) we currently have for missing label (and hint), if a dynamic default is present.

**Comment by gushil** [comment]
@pbowen-oc I'm working on this.
@MartijnR I've created PR #458 to address this issue.
