### ISSUE TITLE
Triggers referring to question without form control, are silently ignored

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#452]
This issue refers to the not-yet-released master with trigger support.

type | name | label | trigger | calculation
-- | -- | -- | -- | --
calculate | one |   |   | 5 + 4
calculate | one-ts |   | ${one} | now()
note | note | timestamp: ${one-ts} |   |  

[XLSForm](https://docs.google.com/spreadsheets/d/16Dddg9MXyr-gtXJO68tGtl3oeyLGj2VoSx1NQ4TH2Og/edit?usp=sharing)

In this case there is no `<setvalue>` in the XForm output. This is correct, because ${one} has no form control (i.e. no label and no hint, and therefore no body element).

The form designer should get some feedback. E.g. "Trigger was added for ${one-ts} that refers to hidden question. This is not allowed."

I think an error would be more helpful than a warning in this case. What do others think?

**Comment by pbowen-oc** [comment]
I'd prefer if this were an error. Otherwise, we'll have no way of letting users know that their form won't work as intended.

**Comment by MartijnR** [comment]
Thanks. Looks like this would be ready for a PR.

**Comment by pbowen-oc** [comment]
I think OC can take this.

**Comment by gushil** [comment]
@MartijnR I've created a PR https://github.com/XLSForm/pyxform/pull/457 to resolve this issue. Please review.

Thanks!
