### ISSUE TITLE
type=calculate without a calculation column but with a dynamic default should be allowed

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#454]
Currently there is an error when using:

type | name | label  | calculation | default
-- | -- | -- | -- | --
calculate | a |   |   | random() 

<img width="247" alt="Screen Shot 2020-06-24 at 2 50 22 PM" src="https://user-images.githubusercontent.com/627350/85626396-38708000-b62a-11ea-99ac-cc976d0a0995.png">

But I think this should be allowed as it is the equivalent of 

type | name | label  | calculation | default
-- | -- | -- | -- | --
text | a |   |   | random()

**Comment by gushil** [comment]
@MartijnR PR #456 available to fix this issue.

Thanks.
