### ISSUE TITLE
Store pyxform.survey.Survey "_translations" in an OrderedDict

### ISSUE THREAD

**Issue by dorey** [XLSForm/pyxform#459]
I'm creating this issue with a corresponding commit to discuss a (possible) improvement to the code.

The `pyxform.Survey` object builds the `<itext>` block by parsing the survey data and generating a corresponding `<translation>` element.

* `self._translations`  is a `collections.defaultdict(dict)` which doesn't maintain the order of the keys. (_see "caveat" below_)
* `self._translations` is created after the `survey.to_xml()` method is called. So, if a 3rd party python script wants to set the order of these translation after the object has been created but before `survey.to_xml()`, it's not possible.

I'm proposing--

* we create `survey._translations` as an `OrderedDict()` when the survey is instantiated. This way, a script can , at the very least, set the order on its own.
* we can then rely on XForms generated with this script to order `<translation>` elements consistently (in the order in which they appear in the XLSForm's survey columns, I believe)

---
`*` *Caveat*: This might not be necessary in python3.7+ because `dict` and `defaultdict` now retain key order. But since we aren't setting a python version requirement, we can't depend on this behavior.

**Comment by lindsay-stevens** [comment]
Was resolved in 68f0db9. Since then, it's now a defaultdict, which is OK because only Python 3.7+ is supported and so the dict retains key insertion order. In any case it's not clear from the description why retaining key order is important, either to pyxform or the XForm output.
