### ISSUE TITLE
Add value and label params to select_.._from_file

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#461]
#### Problem description

When creating select options from external (and internal) data in XLSForm, the "name" and "label" data columns are hardcoded in the XForm output (and therefore required in the data), when using:

* select_one_from_file filename.csv & select_one_from filename.xml
* select_multiple_from_file filename.csv & select_multiple_from filename.xml

This means that you'd normally have to modify the data file to rename columns (or XML nodes), which is not great.

This is purely a pyxform/xlsform restriction because Collect, Enketo, iXForms etc are perfectly capable to deal with other names.

Discussion: https://forum.getodk.org/t/proposal-customize-name-and-label-columns-in-selects-from-external-data-in-xlsform/27265

#### Feature

Customize value and label names using the `parameters` column:

##### 1
| type | parameters | name | label |
|-------|-----------------|---------|--------|
| select_multiple_from_file hh-data.csv | value=hh_number, label=hh_name | a | Select |

##### 2
| type | parameters | name | label |
|-------|-----------------|---------|--------|
| select_one_from_file hh-data.csv | value=hh_number, label=hh_name | a | Select |

##### 3
| type | parameters | name | label |
|-------|-----------------|---------|--------|
| select_multiple_from_file hh-data.xml | value=hh_number, label=hh_name | a | Select |

##### 4
| type | parameters | name | label |
|-------|-----------------|---------|--------|
| select_one_from_file hh-data.xml | value=hh_number, label=hh_name | a | Select |

Output includes (for all 4 cases): 

```xml
<itemset nodeset="instance('hh-data')/root/item">
       <value ref="hh_number" />
       <label ref="hh_name" />
</itemset>
```

**Comment by lognaturel** [comment]
We further discussed and came up with some additions at https://forum.getodk.org/t/proposal-customize-name-and-label-columns-in-selects-from-external-data-in-xlsform/27265/9 to support multilingual labels. I think this is still the right place to start and will "just work" for clients.

Then the translations can be layered on. I believe they will require changes to the XForms spec (add `local-name()` and allow some expressions for itemset label refs) for all clients. Does that sound right, @MartijnR?

**Comment by MartijnR** [comment]
> Then the translations can be layered on. I believe they will require changes to the XForms spec (add local-name() and allow some expressions for itemset label refs) for all clients. Does that sound right, @MartijnR?

Yes!

**Comment by lindsay-stevens** [comment]
Hi @lognaturel and @MartijnR - would it be safe to proceed with implementing the single-language specification described in this ticket?

From the linked forum thread it looks like the multi-language case is pretty much a direct extension of this syntax. The changes being what `itext` content and `value`/`label` refs are emitted by pyxform. However that extension seems to require both XForms spec updates and forms app (Collect / Enketo / etc) compatibility. On the former I couldn't see a PR or issue in the getodk/xforms-spec repo.

In terms of how pyxform might handle the multi-language case, maybe it could be via language-specific parameter columns. Users would be familiar with the concept from the many other columns that accept a language designation. This might also simplify the new pyxform code by following the same pattern. There is a repeated `value` key there but maybe that's actually a feature via allowing language-specific values from the same file. For example:

| type  | name | label::English (en) | label::French (fr) | parameters::English (en) | parameters::French (fr) |
| -| -| -|-|-| - |
| select_one_from_file my_data.csv  | tree  | Tree | Arbre | value=id, label=species | value=id, label=espèces |

**Comment by MartijnR** [comment]
thanks @lindsay-stevens!

We should wait to hear what @lognaturel or @yanokwa thinks but fwiw, after revisiting the proposals, I think proceeding without translations would be fine as a first step. 

The proposal for the separate parameter columns might be problematic (lose its elegance) when also using parameters that are not translatable like `randomize=true, seed=${sd}`.

**Comment by lindsay-stevens** [comment]
Thanks @MartijnR, perhaps the `parameters` column follow the behaviour of other translatable columns, in that a default `parameters` column could exist alongside non-default translation columns such as `parameters::French`. So non-translatable parameters could go in `parameters`, and translatable parameters could go in e.g. `parameters::French`.

**Comment by lognaturel** [comment]
For now, the goal would be to add support for just value and label parameters. With the spec we’d come up with, that can happen independently of the translation solution which would be layered on later. 

Please note that the values column is fixed across languages. @martijnr and I discussed this spec quite a bit although it’s not fully captured in the forum thread. We used [this doc](https://docs.google.com/spreadsheets/d/1Louqe61dXPrx9iRDp-9sV5P1T9wKNvM4Z3mycAj55Ac/edit) for notes and on the choices sheet you can see a proposal with separate language columns that we explored briefly. @MartijnR convinced me on the approach we ended up with by pointing out that it’s unusual to have many languages in a single data file and it’s useful to see the meaning of all csv columns at a glance.

Adding parameters::Lang columns doesn’t make sense to me because it’s unlikely we’d ever have a use for them other than for external file labels. If we were going that direction, I think the column names should reflect their semantics ( e.g ext_file_label::lang). I think the proposal from the notes doc where the columns are defined in the choices sheet makes more sense but it does mean introducing some new concepts. @martijnr may also have had stronger arguments against it than I remember. 

If there’s a desire to explore the spec further, that conversation should go in the forum thread.

**Comment by lognaturel** [comment]
@lindsay-stevens What do you think? Do you feel like moving ahead with just label and value for now is reasonable? It would bring a fair amount of value. It does limit what the translation spec could reasonably look like, though, so if you have strong objections to what @MartijnR and I came up with, it's good to hear them.

**Comment by lindsay-stevens** [comment]
@lognaturel yep sounds good thanks, I'll proceed with the spec described in the OP. If it looks like it'll be problematic I'll add that feedback here.

**Comment by lindsay-stevens** [comment]
Using a custom value / label via parameters throws an ODK Validate error. This seems to be related to https://github.com/getodk/validate/pull/74 where the related validation uses a faked instance with hard-coded name / label.

Not sure how to work around this yet - maybe a stub instance structure in the XForm would work, or maybe an ODK Validate change for the relevant validation is required (or removing that validation).

Error from ODK Validate
```
: <label> node for itemset doesn't exist! [instance(neighbourhoods)/root/item/lbl]
```
XLSForm
```
md = """
        | survey |                                              |                      |                |                |
        |        | type                                         | parameters           | name           | label          |
        |        | select_one_from_file cities.csv              | value=val, label=lbl | city           | City           |
        |        | select_multiple_from_file neighbourhoods.csv | value=val, label=lbl | neighbourhoods | Neighbourhoods |
"""
```
XML
```
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events"
 xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" 
xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>pyxform_autotesttitle</h:title>
    <model odk:xforms-version="1.0.0">
      <instance>
        <test id="pyxform_autotest_id_string">
          <city/>
          <neighbourhoods/>
          <meta>
            <instanceID/>
          </meta>
        </test>
      </instance>
      <instance id="cities" src="jr://file-csv/cities.csv"/>
      <instance id="neighbourhoods" src="jr://file-csv/neighbourhoods.csv"/>
      <bind nodeset="/test/city" type="string"/>
      <bind nodeset="/test/neighbourhoods" type="string"/>
      <bind jr:preload="uid" nodeset="/test/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <select1 ref="/test/city">
      <label>City</label>
      <itemset nodeset="instance('cities')/root/item">
        <value ref="name"/>
        <label ref="label"/>
      </itemset>
    </select1>
    <select ref="/test/neighbourhoods">
      <label>Neighbourhoods</label>
      <itemset nodeset="instance('neighbourhoods')/root/item">
        <value ref="val"/>
        <label ref="lbl"/>
      </itemset>
    </select>
  </h:body>
</h:html>
```
The CSV files don't exist.

**Comment by lognaturel** [comment]
I had completely forgotten about that. It certainly complicates things. JavaRosa currently needs an instance in memory to verify that the expected nodes exist. It might be possible to do away with the verification and have it fail later but I’m not sure how significant of a change that will be. 

I have some childcare now and am transitioning back to a bigger workload. I have some other priorities to tend to unfortunately and then I’d like to review your open PR before giving this more thought.

**Comment by lognaturel** [comment]
> JavaRosa currently needs an instance in memory to verify that the expected nodes exist.

Just kidding, I addressed that a while back and... got my entire brain wiped since, apparently.

https://github.com/getodk/validate/pull/86 should remove the Validate stubbing that was getting in the way. Hoping we can get a release of that out in the next couple of days so you can move forward.
