### ISSUE TITLE
Mixed variable and Urdu label result in misordered layout

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#47]
I want to have the following
`Q6. صوبہ ؟ ${province} کیا`

I put this in the XLSForm:
<img width="200" alt="screen shot 2015-09-05 at 07 29 59" src="https://cloud.githubusercontent.com/assets/32369/9699036/f563f720-539f-11e5-9eb8-fa9dc9a862fa.png">

It shows up in the XML like this:
<img width="568" alt="screen shot 2015-09-05 at 07 29 50" src="https://cloud.githubusercontent.com/assets/32369/9699037/fe8e4e5e-539f-11e5-8d8d-94ee30a2e589.png">

It shows up this in ODK Collect like this:
<img width="352" alt="output" src="https://cloud.githubusercontent.com/assets/32369/9699019/36a2fa0c-539f-11e5-96eb-1fa0dd9e752e.png">

Note Accra (the province) is moved to the end...

**Comment by ukanga** [comment]
@yanokwa What should be the expected xml?

**Comment by yanokwa** [comment]
I think it should look like this:
```<value> Q6. صوبہ ؟ <output value="/urdu_test/province"/> کیا </value>```

**Comment by dorey** [comment]
I tried to verify this issue [here](https://github.com/XLSForm/pyxform/commit/cde6b323f96df71b4746ad471c58f8b597bfb78b#diff-8b6271e95381ffaed30c4c7b8a2a2c1eR31), but I might not be understanding RTL text...

**Comment by dorey** [comment]
How about just a warning for any translations that are mixed to discourage the user above from putting "Accra" and "Q6." in the Arabic translation?

**Comment by yanokwa** [comment]
pyxform is misordering the input so I don't think a warning is sufficient.

**Comment by dorey** [comment]
I'm trying, but I can't see how pyxform is ordering it incorrectly. I think it's either incorrect input or collect's issue in rendering LTR + RTL + LTR + RTL text.

When I have tried pasting the examples you listed into [this spreadsheet](https://docs.google.com/spreadsheets/d/1bmpigkUycvNvusCbSGfYeNlFJUze8qgrXkAOls0z_O0/edit?usp=sharing), the XML was how i would expect it:

```<label>Q6. صوبہ ؟ <output value=" /mixed_rtl_example/province "/> کیا</label>```

I'm comparing that to your pasted output in this comment--

> I think it should look like this:
> ```<value> Q6. صوبہ ؟ <output value="/urdu_test/province"/> کیا </value>```

and aside from whitespace, tag names, and the xpath, the strings are the same.

So, if there is a pyxform bug here, I'm not able to see it. Feel free to edit the doc with notes about what's not right.

**Comment by yanokwa** [comment]
Use Excel, not Google Docs. Attached is sample input and output.

**Comment by tinok** [comment]
I've had the same issue previously in Excel, which sometimes changes the
sequence of RTL and LTR text (even between what is shown on the screen and
how it's saved in the file). I found this was especially bad when using
formulas.

I'd suggest we test this based on a CSV file to make sure it's not a
pyxform bug.

**Comment by yanokwa** [comment]
Had to do some hackery to get this CSV working and doesn't look like it does in Excel. Anyone know someone who speaks a RTL language that can test these things?
[urdu.txt](https://github.com/XLSForm/pyxform/files/29590/urdu.txt)

**Comment by saffanhamdani1** [comment]
I am a native urdu speaker and want to contribute. Can you please guide me further how to proceed?

**Comment by dorey** [comment]
It's a bit of a messy example, but could you provide a screenshot of how the urdu translation of the string:
`Q6. Which state in ${province}?`
should look? (Noting that `${province}` gets replaced with the response to a previous question)

**Comment by saffanhamdani1** [comment]
To my understanding it should look like "میں کونسی ریاست  ؟ ${province} Q6."
I have also been struggling a lot when it comes to mixed usage of LTR+RTL text. 
I prefer then not to mix them.

**Comment by sadiqkhoja** [comment]
This is not pyxform issue and can be safely closed.

It is the way bidirectional text is displayed in excel and gsheet. When setting bidirectional label we have to make sure the text direction of the cell is left-to-right:

![image](https://github.com/XLSForm/pyxform/assets/447837/84efc3ae-f049-4f2c-87f9-d7dd85a5898a)

Enketo:

![image](https://github.com/XLSForm/pyxform/assets/447837/267b3cbe-0991-4fd0-8ecb-11c202347994)

Collect:

<img width="400" src="https://github.com/XLSForm/pyxform/assets/447837/916b5dda-a66d-4f03-b8b1-bfe01b462520"/>

**Comment by lognaturel** [comment]
Thank you, @sadiqkhoja!
