### ISSUE TITLE
Display warning when using simserial or subscriberid

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#471]
Related docs issue: https://github.com/XLSForm/xlsform.github.io/pull/208

Web-based clients such as Enketo have never been able to read permanent unique identifiers like simserial or subscriberid. Neither have iOS clients for a long time. Android clients used to be able to access them but won't be able to do so from Play Store installs starting Nov 2020.

That means the only clients that will be able to access these identifiers are Android clients that target and run on Android versions < 11 (e.g. old versions of Collect). 

<strike>@MartijnR pointed out at https://github.com/XLSForm/xlsform.github.io/pull/208#issuecomment-693499567 that maybe we should show an error when a user attempts to use these. Given that some folks might intentionally stay on old client versions to access this behavior, I have a slight preference for warning.

- [x] decide whether to warn or error
- [x] decide on text</strike>

From https://github.com/XLSForm/pyxform/issues/471#issuecomment-693531176:
Warning with text "Simserial is no longer supported on most devices. Only old versions of Collect on Android versions older than 11 still support it." (same for subscriberID)

**Comment by MartijnR** [comment]
> Given that some folks might intentionally stay on old client versions to access this behavior, I have a slight preference for warning.

Yes, that's a good reason. Warning sounds sensible.


"Simserial is no longer supported on most devices. Only old versions of Collect on Android versions older than 11 still support it." (same for subscriberID)

**Comment by KeynesYouDigIt** [comment]
Should we also note the alternatives? eg "Consider using deviceId or Phone Number" ?
