### ISSUE TITLE
Only show repeat warning when there are repeats

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#476]
pyxform shows the below warning regardless of if I have repeats. It's a bit irritating!

>Repeat behavior has changed. Previously, some clients like ODK Collect prompted users to add the first repeat. Now, the user will only be prompted to add repeats after the first one. Representing 0 repetitions will require changing the form design. Read more at http://xlsform.org#representing-zero-repeats.

**Comment by yanokwa** [comment]
Whoops. I was looking at the wrong form.

**Comment by lognaturel** [comment]
The latest pyxform version shouldn't have this warning anymore. Which version are you using?

**Comment by yanokwa** [comment]
It was on Central v1.0.0.
