### ISSUE TITLE
When indexed-repeat is used within a repeat the first argument nodeset points to single node using relative path

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#484]
#### Software and hardware versions 
2.2.1

#### Problem description
The first argument of indexed-repeat() calls is relative when called from inside a repeat and referring to a question in that repeat. It should be absolute.

A `../relative/path/to/question` always returns a single node (in ODK XForms) and according to [the spec](https://getodk.github.io/xforms-spec/#fn:indexed-repeat) it should refer to all nodes with that question name, i.e. the nodeset returned by `/absolute/path/to/question`.

#### Steps to reproduce the problem

_A. using regular calculation with relative index:_

type | name | label | calculation
-- | -- | -- | --
begin_repeat | person | Person |  
integer | pos | | position(..) |
text | name | Enter name |  
text | prev_name | Name in previous repeat instance | indexed-repeat(${name}, ${person}, ${pos}-1)
end_repeat |   |   |  

outputs: 

```xml
<bind calculate="indexed-repeat( ../name ,  /data/person , ../pos -1)"  ... />
```

_B. using dynamic default:_

type | name | label | default
-- | -- | -- | --
begin_repeat | person | Person |  
text | name | Enter name |  
text | prev_name | Name in previous repeat instance | indexed-repeat(${name}, ${person}, position(..)-1)
end_repeat |   |   |  

outputs:

```xml
<setvalue ... value="indexed-repeat( ../name ,  /data/person , position(..)-1)" />
```

_C. using dreaded nested repeats:_

type | name | label | default
-- | -- | -- | --
begin_repeat | family | Family |  
integer | members_number | How many members in this family? |  
begin_repeat | person | Person |  
text | name | Enter name |  
text | prev_name | Non-sensible previous name in first family, 2nd person | indexed-repeat(${name}, ${family}, 1, ${person}, 2)
end_repeat |   |   |  
end_repeat |   |   |  

outputs:

```xml
<setvalue .. value="indexed-repeat( ../name ,  /data/family , 1,  ../../person , 2)" />
```

#### Expected behavior

A:

```xml
<bind calculate="indexed-repeat( /data/person/name ,  /data/person , ../pos - 1)" ... />
```

B: 
```xml
<setvalue ... value="indexed-repeat( /data/person/name ,  /data/person , position(..)-1)" />
```

C: 
```xml
<setvalue .. value="indexed-repeat( /data/family/person/name ,  /data/family , 1, /data/family/person , 2)" />
```

So the first argument of indexed-repeat() is an exception to the relative-path rule used to transform ${node} syntax (and the second argument too but that seems to already be the case).

Or actually since indexed-repeat() has either 3, 5, or 7 arguments, this exception applies to the 1st, 2nd, 4th, and 6th  arguments.

#### Other information 

Previously using indexed-repeat() inside a repeat was a bit of an edge case. Since the introduction of dynamic defaults it is becoming more common, as you could use the answer of a previous repeat question as the dynamic default of that same question in a new repeat instance (example B).

I'm guessing this issue was introduced in 0.12.0 when we changed to relative node references inside repeats.

**Comment by MartijnR** [comment]
ping @pbowen-oc

**Comment by MartijnR** [comment]
will add a third example with dreaded nested repeats

**Comment by pbowen-oc** [comment]
Thanks for logging this, @MartijnR

@gushil - Can you please work on this?

**Comment by gushil** [comment]
@pbowen-oc Working on it.

**Comment by gushil** [comment]
Hi @MartijnR, I've created PR #485 to fix this issue. Waiting for review.
Thanks

**Comment by MartijnR** [comment]
Looks like the form posted here slips through the cracks: https://github.com/OpenClinica/enketo-express-oc/issues/398#issuecomment-745082006 .  See both (similar) indexed-repeat() calls.

One of them is:
`if(position(..) = 1, '', indexed-repeat(${bp_sys}, ${bp_rg}, position(..) - 1))`

**Comment by pbowen-oc** [comment]
@gushil - Can you take a look at this?

**Comment by gushil** [comment]
@pbowen-oc working on it

**Comment by gushil** [comment]
@MartijnR I've created a new PR (#499) to solve the issue @pbowen-oc mentioned.

Thanks.
