### ISSUE TITLE
select_one_external only works if choice_filter is not empty

### ISSUE THREAD

**Issue by qlands** [XLSForm/pyxform#488]
PyXForm crashes with a key error if select_one_external does not have a choice_filter

```
  File "/home/cquiros/data/projects2017/personal/software/pyxform/pyxform/xls2json.py", line 1205, in workbook_to_json
    new_json_dict[constants.CHOICES] = choices[list_name]
KeyError: 'counties'

```
If I correct the code to allow empty choice_filter then ODK Collect crashes with message "Error Ocurred length=30; regionStart=0; regionLength=-1"

I also tried by having a filter column called my_filter and set all items to 1 and then using in "choice_filter" my_filter=1  . But this ended in an empty select in ODK Collect.

Using PyXForm 1.2.1 and Master
ODK Collect 1.28.4

**Comment by lognaturel** [comment]
Thanks! I believe this is a duplicate of https://github.com/XLSForm/pyxform/issues/387

**Comment by qlands** [comment]
OK. Cool.
