### ISSUE TITLE
Do not url encode HTML namespaced tags

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#52]
When I put the following in an XLSForm's label or hint

``` xml
<h:font color="red">red </h:font>
<h:font color="#f58a1f">#f58a1f </h:font>
<h:p>
    <h:font face="monospace">monospace </h:font>
</h:p>
```

I get this in the XML:

``` html
&lt;h:font color=&quot;red&quot;&gt;red &lt;/h:font&gt;
&lt;h:font color=&quot;#f58a1f&quot;&gt;#f58a1f &lt;/h:font&gt;
&lt;h:p&gt;
    &lt;h:font face=&quot;monospace&quot;&gt;monospace &lt;/h:font&gt;
&lt;/h:p&gt;
```

Tags with the h namespace (`<h:`) should be passed through.

**Comment by MartijnR** [comment]
Why? Am just trying to understand the use case here. The examples can be achieved in the new Markdown (span) support, right?

Any (X)HTML support would potentially mess up stuff in web clients, so I am really happy with XLSForm converting all tags.

**Comment by yanokwa** [comment]
Thought about it some more and @MartijnR is probably right. I think span does all that is needed at this point. I'll leave this open for a week or so to see if anyone else might have a reason for pass through HTML.
