### ISSUE TITLE
Warn if worksheet titles are not lowercase

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#527]
An XLSForm with a "Survey" sheet fails with "The survey sheet is either empty or missing important column headers", but the same form with a "survey" sheet works.

I'm not sure there is a good reason for this. I propose we make the check case-insensitive, but perhaps convert it to lowercase immediately so we don't break anything downstream. Or maybe we just warn if any of constants.SUPPORTED_SHEET_NAMES are not all lowercase.

**Comment by lognaturel** [comment]
I'd be in favor of normalizing case of sheet names to accept whatever case people use.

Related to #443.
