### ISSUE TITLE
allow "value" as an alias for "name" in survey sheet

### ISSUE THREAD

**Issue by dorey** [XLSForm/pyxform#54]
see discussion in [odk-developers group](https://groups.google.com/forum/#!topic/opendatakit-developers/BZKVfQkotjo)

**Comment by mberg** [comment]
Why not add an extra column?

**Comment by dorey** [comment]
For a little while, `value` was accepted as an alias of `name` which is clearer for the end user. But in [this commit in 2013](https://github.com/XLSForm/pyxform/commit/0ec4ea65b9fd6f3dcb35516ef0b8d7ae5effec48) we started checking against a more specific set of columns.

It's doing this to ensure that the sheets are not missing the top row with the column names, and so the user gets a clear error when they omit it, but this goes against the simplicity of the worksheet dict and has caused some minor bugs during testing. I'm looking into an alternative that avoids using `"%s_header"` items in the worksheet_dict.

**Comment by ukanga** [comment]
closed by #55

**Comment by dorey** [comment]
I will edit this test to specifically test the use of `value` on the choices sheet , which is what the original discussion referred to.
