### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#555]
Python 3.9 has been out since Oct 2020. We should add support for it in our build scripts along with Python 3.7 and 3.8.

- [x] Figure out what to do about xls support (https://github.com/XLSForm/pyxform/issues/501)
- [ ] .appveyor.yml
- [ ] .circleci/config.yml
- [ ] .github/workflows/pypi.yml

**Comment by lindsay-stevens** [comment]
Note #501 about xlrd support for 3.9
