### ISSUE TITLE
Use of _count in variable name results in duplicate survey element error

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#576]
#### Software and hardware versions 
pyxform v1.7.0

#### Steps to reproduce the problem

1. Upload [circuit_first.xlsx](https://github.com/XLSForm/pyxform/files/7658076/circuit_first.xlsx) to https://getodk.org/xlsform/.
   <img width="550" alt="Screen Shot 2021-12-05 at 20 59 38" src="https://user-images.githubusercontent.com/32369/144789837-5621cc6d-a77d-4dcf-b99c-f9f9f45d0bc6.png">
2. You will get this error: `Error: There are more than one survey elements named 'circuit_count' (case-insensitive) in the section named 'data'.`
3. If you replace `circuit_count` with `circuit_countx`, the form converts with no problems.
   <img width="564" alt="Screen Shot 2021-12-05 at 21 04 08" src="https://user-images.githubusercontent.com/32369/144790266-6579360c-e3e2-4da9-9d5a-ba5ac1d7f158.png">

**Comment by lognaturel** [comment]
Related: https://github.com/XLSForm/pyxform/issues/435

**Comment by lognaturel** [comment]
This is indeed annoying and pretty easy to run into. I think we should look at addressing @MartijnR's case 1 in https://github.com/XLSForm/pyxform/issues/435: if the `repeat_count` is a simple reference, just use the ref and don't introduce another one.
