### ISSUE TITLE
Add accuracyThreshold and unacceptableAccuracyThreshold as parameters for geopoint

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#579]
There's no explicit `pyxform` support for `accuracyThreshold` now though the XLSForm site documents it using the generic body attribute column structure: https://xlsform.org/en/#gps-with-accuracythreshold Adding it to the parameter column as `capture-accuracy` will make it more accessible.

`unacceptableAccuracyThreshold` is new to ODK Collect. It configures a threshold for the worst accuracy that will be labeled as "unacceptable" to help encourage data collectors to wait or improve conditions for a higher-accuracy point.

| XForms attribute              | XLSForm parameter |
|-------------------------------|-------------------|
| accuracyThreshold             | capture-accuracy  |
| unacceptableAccuracyThreshold | warning-accuracy  |

**Comment by lognaturel** [comment]
Good question! No, the `body::` and `bind::` things are generic tools. Whatever is after the `::` gets passed in to the body or bind, respectively. I imagine they were introduced as both a stopgap for XForms features that get introduced and for flexibility for custom clients.

**Comment by seadowg** [comment]
I'm thinking `capture-accuracy` (and `unacceptable-accuracy` for the other threshold we've talked about) make sense as names here!

**Comment by lindsay-stevens** [comment]
Some options for unacceptable in `unacceptable-accuracy`: invalid, lowest, minimum.

**Comment by lognaturel** [comment]
Thanks, @lindsay-stevens, talking it through was helpful. How about `warn-accuracy`: the unacceptable threshold represents a threshold above which clients are encouraged to warn the user to change conditions or keep waiting.

I'm proposing `warn-accuracy` rather than `warning-accuracy` by analogy to `capture-accuracy`.
