### ISSUE TITLE
appearance=table-list breaks if additional appearance is added

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#61]
Appearance `table-list` is properly detected, resulting correctly in inputs with `appearance="label"` and `appearance="list-nolabel"`

However, when adding another appearance, e.g. `table-list something`, it appears to not be detected. The output does not add `appearance="label"` and `appearance="list-nolabel"` to inputs in this group.

[test form](https://docs.google.com/spreadsheets/d/1iCU1xcu_76xJ0FLSRg4OEzRp_ccMImFaAWqQw_ko8GI/edit#gid=0)

Background: just something I happened to see when testing the boundaries of a new 'random' feature for select and select1 questions. 'appearance="random" is not actually planned to be supported in tables  ~~at least not initially~~ ever. 

### Update:

**a `randomize()` XPath function was introduced instead which is much better. This issue still stands though**

**Comment by lognaturel** [comment]
> 'appearance="random" is not actually planned to be supported in tables - at least not initially.

There is no such appearance. Appearances are generally passed through so you should be able to test with any text including "random." Note that `table-list` is NOT just passed through, that's why there are issues related to it.

**Comment by KeynesYouDigIt** [comment]
Looking now but JIC you know off the top of your head - is this attribute actually tested somewhere already where I can extend the test? I see the table-list xls fixture but cant find any references to it in the test code.

**Comment by MartijnR** [comment]
This what you are looking for @KeynesYouDigIt ? https://github.com/XLSForm/pyxform/blob/1493706622c329fd2913ae691a902bca054250d4/pyxform/tests_v1/test_randomize_itemsets.py

Just confirming that my issue above is confusing. Sorry about that. Using an appearance to randomize was abandoned in favor of the much better `randomize()` XPath function. Will update it to make that clear.

**Comment by KeynesYouDigIt** [comment]
@MartijnR I see the difference in XML out put but not in enketo's actualy display of the data. I think I can track down the source and submit a PR soon, but is there a clean way I could actally reproduce the enketo display diff as well as the xml diff? shoot me a slack if that question doesnt make sense :smile: :smile: so glad to finally start grasping this eco system

**Comment by lognaturel** [comment]
Hmm, now that I think about it, I think this is more of a theoretical concern than a practical one. That is, I can’t think of any actual, existing appearance that combines with list-nolabel. Do you know of one, @martijnr?

Ultimately, fixing the XML output is what we’re after and it would be great to address for any future appearance combinations that may come up.

**Comment by lognaturel** [comment]
> @KeynesYouDigIt If randomize() doesn't appear to be working, try uploading to opendatakit.org/xlsform and clicking the Enketo preview. If it doesn't work there, please report a bug in enketo/enketo-core with the test form. Thanks! (Note KoBoToolbox's public servers are still using an older version of pyxform).

This specific issue has nothing to do with randomize, though, right? It was discovered when `randomize` was going to be an appearance but that's no longer the case.

It would be sufficient, I think, to make sure that if the XLSForm appearance is `table-list something` or `something table-list`, the output includes appearance="something" on the group and that selects with `appearance="list-nolabel"` and `appearance="label"` are generated. Clients wouldn't show any change in behavior but the XML can be verified.

I'd also be ok with closing.

**Comment by KeynesYouDigIt** [comment]
I do see a difference in the xml output that looks significant, but @ me if this ends up getting closed. I have enough time to poke at it a bit today

**Comment by KeynesYouDigIt** [comment]
![](https://media.giphy.com/media/vuNmxT8OCVXv89itOh/giphy.gif)
