### ISSUE TITLE
Warning given when converting a form with choices option with `image` but no `label`

### ISSUE THREAD

**Issue by jkuester** [XLSForm/pyxform#610]
#### Software and hardware versions 
pyxform v1.10.0, Python 3.8.10

#### Problem description

When converting a form that has options specified on the "choices" sheet that have a value for `image` but not for `label`, I see a warning:

```
Warnings:
On the choices sheet there is a option with no label. [list_name : a_b]
```

This happens when following the pattern from the [example Enekto Widgets form](https://enke.to/x/widgets) where you can have a select question where the user picks based on images and there are no labels:

![image](https://user-images.githubusercontent.com/8441903/172408985-47b847ad-f757-42fa-825c-5c58c8f285f6.png)
 
#### Steps to reproduce the problem

1. Download the [example Enketo Widgets form](https://docs.google.com/spreadsheets/d/1KLQiQyQ5BlN_wd-83p8Eb6xIU-TZp-yvzgrm20HecRI/edit#gid=1)
2. Convert it with `xls2xform`
3. See warnings

#### Expected behavior

If the option has an `image` value, I would not expect to see a warning when there is no `label` value.

**Comment by lindsay-stevens** [comment]
Could you please add where the example widgets form is linked from? I can't seem to find it on the [xlsforms docs](https://xlsform.org/en/), [reference table](https://xlsform.org/en/ref-table/), or [xforms-spec](https://getodk.github.io/xforms-spec/) pages.

The xlsforms docs page states that the label column is mandatory in [the choices worksheet](https://xlsform.org/en/#the-choices-worksheet):

> The choices worksheet has 3 mandatory columns as well: list name, name, and label.
> - The list name column lets you group together a set of related answer choices, i.e., answer choices that should appear together under a question.
> - The name column specifies the unique variable name for that answer choice.
> - The label column shows the answer choice exactly as you want it to appear on the form. Alternatively, [label translation columns](https://xlsform.org/en/#multiple-language-support) can be used.

However users may ignore warnings if they're sure that the form design is as desired.

If possible please add more info about your use case, particularly if the warning has started showing when it did not before.

**Comment by jkuester** [comment]
@lindsay-stevens Thanks for the response here!  After looking at this some more, I am thinking that this is just an Enekto "feature" that is technically out-of-spec (thanks for your link regarding what is required in the choices worksheet!).  

For the record, I cannot remember exactly where I first ran across the link to that example widgets form. But, it is a [pretty](https://forum.getodk.org/t/enketo-on-mobile-when-offline/30465) [commonly](https://github.com/kobotoolbox/enketo-express/issues/857) [referenced](https://community.kobotoolbox.org/t/adding-hyperlink-in-a-survey-question/1037) example form in Enekto discussions.

An interesting counter-example is the [bird](https://enketo.ona.io/x/Ynv3) [watching](https://docs.google.com/spreadsheets/d/1Rxft3H3xl3M9bLFGR2XhXzt1ucyFmd0qFmOQ6FaqJw4/edit#gid=246559171) form referenced by the xlsform [media docs](https://xlsform.org/en/#media). That form contains a bunch of images in the choices sheet, but they all also have a label (which is then also displayed in the generated form). There is no example of a choice without a label.  

Closing this since there does not seem to be any reason to expect pyxform to support behavior that is out-of-spec....

**Comment by lognaturel** [comment]
It is indeed acceptable to use an image in place of a label for either questions or choices. I think keeping the warning for that case is fine, though, because `pyxform` has no idea what the intent is.

The [no-buttons](https://docs.getodk.org/form-question-types/#select-widget-with-no-buttons-appearance) appearance is intended to build grids of images and is generally used without labels. But `pyxform` generally passes through appearances and does no additional checks based on it so even then I think keeping the warning and avoiding too many special cases is fine.

The original All Widgets form is maintained [here](https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ/edit#gid=0) and linked to from [the Collect repo](https://github.com/getodk/collect/#testing-a-form-without-a-server) and [the ODK docs](https://docs.getodk.org/xlsform/). It could also be linked from the XLSForm doc.

**Comment by lognaturel** [comment]
Huh, there's an Enketo bug -- the `no-buttons` appearance is supposed to not display buttons.
