### ISSUE TITLE
Add rows to parameters column for text type

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#616]
It's been part of the ODK XForms spec forever but is not conveniently exposed.

https://forum.getodk.org/t/odk-collect-text-entry-options-limited-by-single-line-design/37942/6?u=ln

**Comment by lindsay-stevens** [comment]
From this:
type | name | label | body::rows
-- | -- | -- | --
text | tall_box | A tall textbox | 7

To this:

type | name | label | parameters
-- | -- | -- | --
text | tall_box | A tall textbox | rows=7

[Spec](https://getodk.github.io/xforms-spec/#body-attributes) says that rows:

> Specifies the minimum number of rows a string `<input>` field gets.
