### ISSUE TITLE
Reject form with unknown columns in entities sheet

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/pyxform#669]
Currently, unknown columns are ignored on all sheets. This is generally convenient for the `survey` sheet because it makes it straightforward to add commentary or turn certain features off. In the case of the entities sheet (and maybe also the settings sheet), it feels like those patterns are less likely to be used.

Entity-related functionality is generally going to be added by defining new columns. For example, we recently introduced `update_if`. Because extra columns are ignored, using a form with `update_if` with an old version of `pyxform` does convert the form, it just ignores `update_if`. It would be more helpful if those forms were rejected instead. It would also be more inline with the [versioning scheme for the entities spec](https://getodk.github.io/xforms-spec/client-audit-logs) and the fact that other consumers of the spec reject versions of the spec newer than they're aware of.

**Comment by ktuite** [comment]
Because this is about rejecting columns in the special sheets, I think it sounds nice.

It would also have helped that one time I wrote `create_id` instead of `create_if` and it said "that's not a column we recognize".
