### ISSUE TITLE
Non-ascii characters in a question name cause an exception

### ISSUE THREAD

**Issue by spatialdude** [XLSForm/pyxform#68]
When non-ascii characters are in the question name, the conversion fails with an exception such as -

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
```

instead of reporting that the question name is invalid.

**Comment by spatialdude** [comment]
Solution https://github.com/XLSForm/pyxform/issues/68#ref-commit-fbe6b8e is to encode **question_name**

```python
 error_message += " Invalid question name [" + question_name.encode('utf-8') + "] "
```

**Comment by lognaturel** [comment]
I think this can be closed? (Sorry, I commented on the PR before!)
