### ISSUE TITLE
getting error while using pull data

### ISSUE THREAD

**Issue by iahmedani** [XLSForm/pyxform#69]
Dear Team,

I have tried pull data from sample-preloading form provided by ODK website, getting below error.

Error occured during the loading of this form. It is recommended not to use this form for data entry until this is resolved.

Please contact xxxx@xx.abc with the link to this page and the error message below:

FormLogicError: instance "hhplotdetails" does not exist in model

**Comment by MartijnR** [comment]
If you have this error with the latest pyxform, please re-open. Any version after September 7th 2015 (9512ba955d291f5e04d7abfa53f5f7453582005f) should not prompt this error.
