### ISSUE TITLE
pyxform 0.9.22 validation not completing

### ISSUE THREAD

**Issue by JasonIves** [XLSForm/pyxform#7]
**What steps will reproduce the problem?**
1.Install pyxform 0.9.22
2.Run converter
3.Conversion completes but validation does not

**What is the expected output? What do you see instead?**
Successful conversion and validation.  Conversion to XML completes but validation does not.

> Traceback (most recent call last):
>   File "C:\Python27\Lib\site-packages\pyxform\xls2xform.py", line 65, in <module
> 
> ```
> warnings = xls2xform_convert(args.path_to_XLSForm, args.output_path)
> ```
> 
>   File "C:\Python27\Lib\site-packages\pyxform\xls2xform.py", line 22, in xls2xfo
> rm_convert
>     survey.print_xform_to_file(xform_path, validate=True, warnings=warnings)
>   File "C:\Python27\Lib\site-packages\pyxform\survey.py", line 394, in print_xfo
> rm_to_file
>     warnings.extend(check_xform(path))
>   File "C:\Python27\Lib\site-packages\pyxform\odk_validate__init__.py", line 96
> , in check_xform
>     if not _java_installed():
>   File "C:\Python27\Lib\site-packages\pyxform\odk_validate__init__.py", line 43
> , in _java_installed
>     p = Popen(["which","java"], stdout=PIPE)
>   File "C:\Python27\lib\subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified

**What version of the product are you using? On what operating system?**
pyxform 0.9.22 Windows 7 OS

**Please provide any additional information below.**
I could be wrong, I'm not a Unix expert; but it looks to me like this is an issue with a Unix specific command being included in pyxform which doesn't work on Windows.  It is in pyxform/odk_validate/**init**.py, the _java_installed function, the "which" command submitted through Popen.

`def _java_installed():`
`p = Popen(["which","java"], stdout=PIPE)`
`return len(p.stdout.readlines()) != 0`

When I comment out the call for this function, converter and validation both work fine.

**Comment by lindsay-stevens** [comment]
Windows support for this has been fixed for a while, since #63. And since ec28a041 it's using the platform-independent method of just trying to call `java -version` and deciding if it's installed based on that.
