### ISSUE TITLE
Executable name confusion

### ISSUE THREAD

**Issue by mattwigway** [XLSForm/pyxform#721]
#### Software and hardware versions 
pyxform v2.0.3, Python v3.12.5

#### Problem description
The `xls2xform` command is not available after running `pip install pyxform`. Looking at [pyproject.toml](https://github.com/XLSForm/pyxform/blob/master/pyproject.toml#L30) it seems that the executable is now installed with the name `xlsform`, and indeed running `xlsform input.xlsx output.xml` produces the expected results. 

The `xlsform` executable is built from the `xls2xform.py` file, so I wasn't sure which was the intended name; I'd be happy to put together a pull request changing the executable name or the Python file name (and updating the readme), but I wasn't sure which name was preferred.

**Comment by lindsay-stevens** [comment]
Thanks! I have opened a PR to fix this. If you haven't already, please join us on the forum https://forum.getodk.org/
