### ISSUE TITLE
Deeply nested groups effectively freeze pyxform

### ISSUE THREAD

**Issue by chrislrobert** [XLSForm/pyxform#8]
If you have groups nested 5-10 levels deep, pyxform begins to take hours to process the form (on the fastest of systems). It appears that pyxform has frozen completely, but it will eventually complete.

The fix is in section.py. Change this:

```
    return [e.xml_control() for e in self.children if e.xml_control() is not None]
```

To this:

```
    for e in self.children:
        control = e.xml_control()
        if control is not None:
            yield control
```

**Comment by lognaturel** [comment]
Fixed in 6b33230
