### ISSUE TITLE
Smart quotes shouldn't break the pyxform

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#85]
Works: selected(${branch}, 'o')

Doesn't work: selected(${branch}, ‘o’)

[test.xlsx](https://github.com/XLSForm/pyxform/files/487611/test.xlsx)

It'd be good if smart quotes were allowed in labels, but I don't know how this plays with UTF-8 and the XML spec and JavaRosa.

**Comment by dorey** [comment]
Any objections to replacing all of these smart characters with their simpler equivalents?

**Comment by yanokwa** [comment]
I personally don't mind, but a lot of design people really like smart quotes.

**Comment by MartijnR** [comment]
Smart quotes are not supported in XPath 1.0 as far as I know, so replacing might be the only way.

See in browser javascript console:

```js
document.evaluate('string("o")', document.documentElement, document.createNSResolver(document.documentElement), XPathResult.STRING_TYPE, null).stringValue
```

versus:

```js
document.evaluate('string(‘o’)', document.documentElement, document.createNSResolver(document.documentElement), XPathResult.STRING_TYPE, null).stringValue
```
<img width="670" alt="screen shot 2016-09-22 at 10 08 55 am" src="https://cloud.githubusercontent.com/assets/627350/18756329/c8282570-80ac-11e6-899d-57f867fee2aa.png">

**Comment by yanokwa** [comment]
Pretty compelling evidence :)

Sounds like replacing is the right way to go.

**Comment by dorey** [comment]
I'll write a test of this change.
Then fixing it shouldn't be hard, just a matter of finding the best place to do it

**Comment by dorey** [comment]
Should smart quotes in labels be simplified as well? Or just `constraints` and `relevance`?

**Comment by dorey** [comment]
All fancy quote characters in any field in the survey sheet will be replaced.

This change does not touch the `settings` or `choices` sheets. (Should it?)

**Comment by yanokwa** [comment]
I think you should replace smart quotes everywhere. 

Settings has form_title and version and what you enter there will show up in the XML. Ditto with the names and labels in the choices.

**Comment by yixi8524** [comment]
@yanokwa  Why do we need to replace all the smart quotes everywhere? Should we consider about this replace function will change the user's real content in the Form? Like label and hint?

**Comment by fendiaoxiaoshuazi** [comment]
The smart quotes are used in Chinese, I guess other languages also use smart quotes often. Therefore, this conversion may affect the survey content.

**Comment by lognaturel** [comment]
@yixi8524 @fendiaoxiaoshuazi if you are interested in exploring a way to maintain smart quotes within strings and hints, please consider opening a PR! Please verify output with the latest releases of both ODK Collect and Enketo Express.
