### ISSUE TITLE
Warn about invalid URLS

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#90]
As discussed at https://github.com/opendatakit/collect/issues/175, pyxform should probably not allow invalid URLs (e.g., URLS with leading and trailing spaces).

**Comment by WinnyTroy** [comment]
This seems to be handled here:
```
        for key, value in row.items():
            if isinstance(value, basestring):
                row[key] = re.sub(r"( )+", " ", value.strip())

```

This is within the `clean_text_values` function in the `pyxform/xls2json.py` file

**Comment by yanokwa** [comment]
@WinnyTroy Maybe can close this issue out with a test then?
