### ISSUE TITLE
Change /meta/instanceID binding to use preload "uid"

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#94]
Putting this here already. ODK Collect still needs to [add support](https://github.com/opendatakit/collect/issues/83).

Current output:
```xml
<bind calculate="concat('uuid:', uuid())" nodeset="/readonly/meta/instanceID" readonly="true()" type="string"/>
```

New output:
```xml
<bind nodeset="/readonly/meta/instanceID" jr:preload="uid" type="string"/>
```

(the `readonly="true()"` is not required I believe, since this node has no form control)

The problem with the current method is that it doesn't guarantee the instanceID will remain unchanged for a record, which means clients cannot use this to identify a record (a draft record e.g.).

**Comment by MartijnR** [comment]
Also first resolve: https://github.com/opendatakit/odk-xform-spec/issues/47

**Comment by lognaturel** [comment]
Doing some housekeeping and ran back into this. Why not wrap `concat('uuid:', uuid())` in `once()` to make sure it only gets populated when empty? That strikes me as a more flexible approach and it avoids `jr:preload` which I don't think anybody likes.

**Comment by MartijnR** [comment]
That would be an improvement. However, in my (probably controversial) option, `instanceID` and `deprecatedID` (in the openrosa namespace) are the only nodes were 'magic' is appropriate (even if setvalue becomes supported), because it is so fundamental to (most) ODK IM systems. 

So in Enketo, the first thing that happens upon load is to strip the `calculate` attribute from the instanceID bind and completely ignore whatever value it had. That actually fits better with the preload approach (even though we want to get rid of preloaders..  :worried:).

**Comment by MartijnR** [comment]
I see, we can perhaps switch to preload `uid` now, right?
