### ISSUE TITLE
Add setup step to readme.md?

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/pyxform#99]
For python noobs such as myself, that would like to use this, this should maybe go somewhere in the readme.md:

> `python setup.py install`
> `python setup.py develop`

**Comment by alxndrsn** [comment]
Another python ignorant here.  What do these commands do?

**Comment by ukanga** [comment]
@MartijnR the readme has undergone some updates recently, can you please check and see if it warrants closing this issue.

**Comment by ukanga** [comment]
@alxndrsn https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install does have some answers for you. Development mode or production mode.

**Comment by MartijnR** [comment]
Looks good. Thanks! Can be closed I think.
